// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_big.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

/**
 * Protobuf type {@code amstee.flink.formats.proto.test.v1.BigPbMessage}
 */
public final class BigPbMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amstee.flink.formats.proto.test.v1.BigPbMessage)
    BigPbMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BigPbMessage.newBuilder() to construct.
  private BigPbMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BigPbMessage() {
    stringField3_ = "";
    bytesField4_ = com.google.protobuf.ByteString.EMPTY;
    bytesField10_ = com.google.protobuf.ByteString.EMPTY;
    bytesField12_ = com.google.protobuf.ByteString.EMPTY;
    stringField14_ = "";
    bytesField17_ = com.google.protobuf.ByteString.EMPTY;
    stringField19_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BigPbMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amstee.flink.formats.proto.test.v1.TestBigProto.internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amstee.flink.formats.proto.test.v1.TestBigProto.internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amstee.flink.formats.proto.test.v1.BigPbMessage.class, com.amstee.flink.formats.proto.test.v1.BigPbMessage.Builder.class);
  }

  public static final int INT_FIELD_1_FIELD_NUMBER = 1;
  private int intField1_ = 0;
  /**
   * <code>int32 int_field_1 = 1 [json_name = "intField1"];</code>
   * @return The intField1.
   */
  @java.lang.Override
  public int getIntField1() {
    return intField1_;
  }

  public static final int BOOL_FIELD_2_FIELD_NUMBER = 2;
  private boolean boolField2_ = false;
  /**
   * <code>bool bool_field_2 = 2 [json_name = "boolField2"];</code>
   * @return The boolField2.
   */
  @java.lang.Override
  public boolean getBoolField2() {
    return boolField2_;
  }

  public static final int STRING_FIELD_3_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stringField3_ = "";
  /**
   * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
   * @return The stringField3.
   */
  @java.lang.Override
  public java.lang.String getStringField3() {
    java.lang.Object ref = stringField3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringField3_ = s;
      return s;
    }
  }
  /**
   * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
   * @return The bytes for stringField3.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringField3Bytes() {
    java.lang.Object ref = stringField3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringField3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTES_FIELD_4_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString bytesField4_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes bytes_field_4 = 4 [json_name = "bytesField4"];</code>
   * @return The bytesField4.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesField4() {
    return bytesField4_;
  }

  public static final int DOUBLE_FIELD_5_FIELD_NUMBER = 5;
  private double doubleField5_ = 0D;
  /**
   * <code>double double_field_5 = 5 [json_name = "doubleField5"];</code>
   * @return The doubleField5.
   */
  @java.lang.Override
  public double getDoubleField5() {
    return doubleField5_;
  }

  public static final int FLOAT_FIELD_6_FIELD_NUMBER = 6;
  private float floatField6_ = 0F;
  /**
   * <code>float float_field_6 = 6 [json_name = "floatField6"];</code>
   * @return The floatField6.
   */
  @java.lang.Override
  public float getFloatField6() {
    return floatField6_;
  }

  public static final int UINT32_FIELD_7_FIELD_NUMBER = 7;
  private int uint32Field7_ = 0;
  /**
   * <code>uint32 uint32_field_7 = 7 [json_name = "uint32Field7"];</code>
   * @return The uint32Field7.
   */
  @java.lang.Override
  public int getUint32Field7() {
    return uint32Field7_;
  }

  public static final int INT64_FIELD_8_FIELD_NUMBER = 8;
  private long int64Field8_ = 0L;
  /**
   * <code>int64 int64_field_8 = 8 [json_name = "int64Field8"];</code>
   * @return The int64Field8.
   */
  @java.lang.Override
  public long getInt64Field8() {
    return int64Field8_;
  }

  public static final int UINT64_FIELD_9_FIELD_NUMBER = 9;
  private long uint64Field9_ = 0L;
  /**
   * <code>uint64 uint64_field_9 = 9 [json_name = "uint64Field9"];</code>
   * @return The uint64Field9.
   */
  @java.lang.Override
  public long getUint64Field9() {
    return uint64Field9_;
  }

  public static final int BYTES_FIELD_10_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString bytesField10_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes bytes_field_10 = 10 [json_name = "bytesField10"];</code>
   * @return The bytesField10.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesField10() {
    return bytesField10_;
  }

  public static final int DOUBLE_FIELD_11_FIELD_NUMBER = 11;
  private double doubleField11_ = 0D;
  /**
   * <code>double double_field_11 = 11 [json_name = "doubleField11"];</code>
   * @return The doubleField11.
   */
  @java.lang.Override
  public double getDoubleField11() {
    return doubleField11_;
  }

  public static final int BYTES_FIELD_12_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString bytesField12_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes bytes_field_12 = 12 [json_name = "bytesField12"];</code>
   * @return The bytesField12.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesField12() {
    return bytesField12_;
  }

  public static final int BOOL_FIELD_13_FIELD_NUMBER = 13;
  private boolean boolField13_ = false;
  /**
   * <code>bool bool_field_13 = 13 [json_name = "boolField13"];</code>
   * @return The boolField13.
   */
  @java.lang.Override
  public boolean getBoolField13() {
    return boolField13_;
  }

  public static final int STRING_FIELD_14_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stringField14_ = "";
  /**
   * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
   * @return The stringField14.
   */
  @java.lang.Override
  public java.lang.String getStringField14() {
    java.lang.Object ref = stringField14_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringField14_ = s;
      return s;
    }
  }
  /**
   * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
   * @return The bytes for stringField14.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringField14Bytes() {
    java.lang.Object ref = stringField14_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringField14_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOAT_FIELD_15_FIELD_NUMBER = 15;
  private float floatField15_ = 0F;
  /**
   * <code>float float_field_15 = 15 [json_name = "floatField15"];</code>
   * @return The floatField15.
   */
  @java.lang.Override
  public float getFloatField15() {
    return floatField15_;
  }

  public static final int INT32_FIELD_16_FIELD_NUMBER = 16;
  private int int32Field16_ = 0;
  /**
   * <code>int32 int32_field_16 = 16 [json_name = "int32Field16"];</code>
   * @return The int32Field16.
   */
  @java.lang.Override
  public int getInt32Field16() {
    return int32Field16_;
  }

  public static final int BYTES_FIELD_17_FIELD_NUMBER = 17;
  private com.google.protobuf.ByteString bytesField17_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes bytes_field_17 = 17 [json_name = "bytesField17"];</code>
   * @return The bytesField17.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesField17() {
    return bytesField17_;
  }

  public static final int BOOL_FIELD_18_FIELD_NUMBER = 18;
  private boolean boolField18_ = false;
  /**
   * <code>bool bool_field_18 = 18 [json_name = "boolField18"];</code>
   * @return The boolField18.
   */
  @java.lang.Override
  public boolean getBoolField18() {
    return boolField18_;
  }

  public static final int STRING_FIELD_19_FIELD_NUMBER = 19;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stringField19_ = "";
  /**
   * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
   * @return The stringField19.
   */
  @java.lang.Override
  public java.lang.String getStringField19() {
    java.lang.Object ref = stringField19_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringField19_ = s;
      return s;
    }
  }
  /**
   * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
   * @return The bytes for stringField19.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringField19Bytes() {
    java.lang.Object ref = stringField19_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringField19_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOAT_FIELD_20_FIELD_NUMBER = 20;
  private float floatField20_ = 0F;
  /**
   * <code>float float_field_20 = 20 [json_name = "floatField20"];</code>
   * @return The floatField20.
   */
  @java.lang.Override
  public float getFloatField20() {
    return floatField20_;
  }

  public static final int FIXED32_FIELD_21_FIELD_NUMBER = 21;
  private int fixed32Field21_ = 0;
  /**
   * <code>fixed32 fixed32_field_21 = 21 [json_name = "fixed32Field21"];</code>
   * @return The fixed32Field21.
   */
  @java.lang.Override
  public int getFixed32Field21() {
    return fixed32Field21_;
  }

  public static final int FIXED64_FIELD_22_FIELD_NUMBER = 22;
  private long fixed64Field22_ = 0L;
  /**
   * <code>fixed64 fixed64_field_22 = 22 [json_name = "fixed64Field22"];</code>
   * @return The fixed64Field22.
   */
  @java.lang.Override
  public long getFixed64Field22() {
    return fixed64Field22_;
  }

  public static final int SFIXED32_FIELD_23_FIELD_NUMBER = 23;
  private int sfixed32Field23_ = 0;
  /**
   * <code>sfixed32 sfixed32_field_23 = 23 [json_name = "sfixed32Field23"];</code>
   * @return The sfixed32Field23.
   */
  @java.lang.Override
  public int getSfixed32Field23() {
    return sfixed32Field23_;
  }

  public static final int SFIXED64_FIELD_24_FIELD_NUMBER = 24;
  private long sfixed64Field24_ = 0L;
  /**
   * <code>sfixed64 sfixed64_field_24 = 24 [json_name = "sfixed64Field24"];</code>
   * @return The sfixed64Field24.
   */
  @java.lang.Override
  public long getSfixed64Field24() {
    return sfixed64Field24_;
  }

  public static final int DOUBLE_FIELD_25_FIELD_NUMBER = 25;
  private double doubleField25_ = 0D;
  /**
   * <code>double double_field_25 = 25 [json_name = "doubleField25"];</code>
   * @return The doubleField25.
   */
  @java.lang.Override
  public double getDoubleField25() {
    return doubleField25_;
  }

  public static final int UINT32_FIELD_26_FIELD_NUMBER = 26;
  private int uint32Field26_ = 0;
  /**
   * <code>uint32 uint32_field_26 = 26 [json_name = "uint32Field26"];</code>
   * @return The uint32Field26.
   */
  @java.lang.Override
  public int getUint32Field26() {
    return uint32Field26_;
  }

  public static final int UINT64_FIELD_27_FIELD_NUMBER = 27;
  private long uint64Field27_ = 0L;
  /**
   * <code>uint64 uint64_field_27 = 27 [json_name = "uint64Field27"];</code>
   * @return The uint64Field27.
   */
  @java.lang.Override
  public long getUint64Field27() {
    return uint64Field27_;
  }

  public static final int BOOL_FIELD_28_FIELD_NUMBER = 28;
  private boolean boolField28_ = false;
  /**
   * <code>bool bool_field_28 = 28 [json_name = "boolField28"];</code>
   * @return The boolField28.
   */
  @java.lang.Override
  public boolean getBoolField28() {
    return boolField28_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (intField1_ != 0) {
      output.writeInt32(1, intField1_);
    }
    if (boolField2_ != false) {
      output.writeBool(2, boolField2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringField3_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stringField3_);
    }
    if (!bytesField4_.isEmpty()) {
      output.writeBytes(4, bytesField4_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleField5_) != 0) {
      output.writeDouble(5, doubleField5_);
    }
    if (java.lang.Float.floatToRawIntBits(floatField6_) != 0) {
      output.writeFloat(6, floatField6_);
    }
    if (uint32Field7_ != 0) {
      output.writeUInt32(7, uint32Field7_);
    }
    if (int64Field8_ != 0L) {
      output.writeInt64(8, int64Field8_);
    }
    if (uint64Field9_ != 0L) {
      output.writeUInt64(9, uint64Field9_);
    }
    if (!bytesField10_.isEmpty()) {
      output.writeBytes(10, bytesField10_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleField11_) != 0) {
      output.writeDouble(11, doubleField11_);
    }
    if (!bytesField12_.isEmpty()) {
      output.writeBytes(12, bytesField12_);
    }
    if (boolField13_ != false) {
      output.writeBool(13, boolField13_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringField14_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, stringField14_);
    }
    if (java.lang.Float.floatToRawIntBits(floatField15_) != 0) {
      output.writeFloat(15, floatField15_);
    }
    if (int32Field16_ != 0) {
      output.writeInt32(16, int32Field16_);
    }
    if (!bytesField17_.isEmpty()) {
      output.writeBytes(17, bytesField17_);
    }
    if (boolField18_ != false) {
      output.writeBool(18, boolField18_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringField19_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, stringField19_);
    }
    if (java.lang.Float.floatToRawIntBits(floatField20_) != 0) {
      output.writeFloat(20, floatField20_);
    }
    if (fixed32Field21_ != 0) {
      output.writeFixed32(21, fixed32Field21_);
    }
    if (fixed64Field22_ != 0L) {
      output.writeFixed64(22, fixed64Field22_);
    }
    if (sfixed32Field23_ != 0) {
      output.writeSFixed32(23, sfixed32Field23_);
    }
    if (sfixed64Field24_ != 0L) {
      output.writeSFixed64(24, sfixed64Field24_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleField25_) != 0) {
      output.writeDouble(25, doubleField25_);
    }
    if (uint32Field26_ != 0) {
      output.writeUInt32(26, uint32Field26_);
    }
    if (uint64Field27_ != 0L) {
      output.writeUInt64(27, uint64Field27_);
    }
    if (boolField28_ != false) {
      output.writeBool(28, boolField28_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (intField1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, intField1_);
    }
    if (boolField2_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, boolField2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringField3_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stringField3_);
    }
    if (!bytesField4_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, bytesField4_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleField5_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, doubleField5_);
    }
    if (java.lang.Float.floatToRawIntBits(floatField6_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, floatField6_);
    }
    if (uint32Field7_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, uint32Field7_);
    }
    if (int64Field8_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, int64Field8_);
    }
    if (uint64Field9_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, uint64Field9_);
    }
    if (!bytesField10_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, bytesField10_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleField11_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, doubleField11_);
    }
    if (!bytesField12_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, bytesField12_);
    }
    if (boolField13_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, boolField13_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringField14_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, stringField14_);
    }
    if (java.lang.Float.floatToRawIntBits(floatField15_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(15, floatField15_);
    }
    if (int32Field16_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, int32Field16_);
    }
    if (!bytesField17_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, bytesField17_);
    }
    if (boolField18_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(18, boolField18_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringField19_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, stringField19_);
    }
    if (java.lang.Float.floatToRawIntBits(floatField20_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(20, floatField20_);
    }
    if (fixed32Field21_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(21, fixed32Field21_);
    }
    if (fixed64Field22_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(22, fixed64Field22_);
    }
    if (sfixed32Field23_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed32Size(23, sfixed32Field23_);
    }
    if (sfixed64Field24_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed64Size(24, sfixed64Field24_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleField25_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(25, doubleField25_);
    }
    if (uint32Field26_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(26, uint32Field26_);
    }
    if (uint64Field27_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(27, uint64Field27_);
    }
    if (boolField28_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(28, boolField28_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amstee.flink.formats.proto.test.v1.BigPbMessage)) {
      return super.equals(obj);
    }
    com.amstee.flink.formats.proto.test.v1.BigPbMessage other = (com.amstee.flink.formats.proto.test.v1.BigPbMessage) obj;

    if (getIntField1()
        != other.getIntField1()) return false;
    if (getBoolField2()
        != other.getBoolField2()) return false;
    if (!getStringField3()
        .equals(other.getStringField3())) return false;
    if (!getBytesField4()
        .equals(other.getBytesField4())) return false;
    if (java.lang.Double.doubleToLongBits(getDoubleField5())
        != java.lang.Double.doubleToLongBits(
            other.getDoubleField5())) return false;
    if (java.lang.Float.floatToIntBits(getFloatField6())
        != java.lang.Float.floatToIntBits(
            other.getFloatField6())) return false;
    if (getUint32Field7()
        != other.getUint32Field7()) return false;
    if (getInt64Field8()
        != other.getInt64Field8()) return false;
    if (getUint64Field9()
        != other.getUint64Field9()) return false;
    if (!getBytesField10()
        .equals(other.getBytesField10())) return false;
    if (java.lang.Double.doubleToLongBits(getDoubleField11())
        != java.lang.Double.doubleToLongBits(
            other.getDoubleField11())) return false;
    if (!getBytesField12()
        .equals(other.getBytesField12())) return false;
    if (getBoolField13()
        != other.getBoolField13()) return false;
    if (!getStringField14()
        .equals(other.getStringField14())) return false;
    if (java.lang.Float.floatToIntBits(getFloatField15())
        != java.lang.Float.floatToIntBits(
            other.getFloatField15())) return false;
    if (getInt32Field16()
        != other.getInt32Field16()) return false;
    if (!getBytesField17()
        .equals(other.getBytesField17())) return false;
    if (getBoolField18()
        != other.getBoolField18()) return false;
    if (!getStringField19()
        .equals(other.getStringField19())) return false;
    if (java.lang.Float.floatToIntBits(getFloatField20())
        != java.lang.Float.floatToIntBits(
            other.getFloatField20())) return false;
    if (getFixed32Field21()
        != other.getFixed32Field21()) return false;
    if (getFixed64Field22()
        != other.getFixed64Field22()) return false;
    if (getSfixed32Field23()
        != other.getSfixed32Field23()) return false;
    if (getSfixed64Field24()
        != other.getSfixed64Field24()) return false;
    if (java.lang.Double.doubleToLongBits(getDoubleField25())
        != java.lang.Double.doubleToLongBits(
            other.getDoubleField25())) return false;
    if (getUint32Field26()
        != other.getUint32Field26()) return false;
    if (getUint64Field27()
        != other.getUint64Field27()) return false;
    if (getBoolField28()
        != other.getBoolField28()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INT_FIELD_1_FIELD_NUMBER;
    hash = (53 * hash) + getIntField1();
    hash = (37 * hash) + BOOL_FIELD_2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolField2());
    hash = (37 * hash) + STRING_FIELD_3_FIELD_NUMBER;
    hash = (53 * hash) + getStringField3().hashCode();
    hash = (37 * hash) + BYTES_FIELD_4_FIELD_NUMBER;
    hash = (53 * hash) + getBytesField4().hashCode();
    hash = (37 * hash) + DOUBLE_FIELD_5_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDoubleField5()));
    hash = (37 * hash) + FLOAT_FIELD_6_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloatField6());
    hash = (37 * hash) + UINT32_FIELD_7_FIELD_NUMBER;
    hash = (53 * hash) + getUint32Field7();
    hash = (37 * hash) + INT64_FIELD_8_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInt64Field8());
    hash = (37 * hash) + UINT64_FIELD_9_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUint64Field9());
    hash = (37 * hash) + BYTES_FIELD_10_FIELD_NUMBER;
    hash = (53 * hash) + getBytesField10().hashCode();
    hash = (37 * hash) + DOUBLE_FIELD_11_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDoubleField11()));
    hash = (37 * hash) + BYTES_FIELD_12_FIELD_NUMBER;
    hash = (53 * hash) + getBytesField12().hashCode();
    hash = (37 * hash) + BOOL_FIELD_13_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolField13());
    hash = (37 * hash) + STRING_FIELD_14_FIELD_NUMBER;
    hash = (53 * hash) + getStringField14().hashCode();
    hash = (37 * hash) + FLOAT_FIELD_15_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloatField15());
    hash = (37 * hash) + INT32_FIELD_16_FIELD_NUMBER;
    hash = (53 * hash) + getInt32Field16();
    hash = (37 * hash) + BYTES_FIELD_17_FIELD_NUMBER;
    hash = (53 * hash) + getBytesField17().hashCode();
    hash = (37 * hash) + BOOL_FIELD_18_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolField18());
    hash = (37 * hash) + STRING_FIELD_19_FIELD_NUMBER;
    hash = (53 * hash) + getStringField19().hashCode();
    hash = (37 * hash) + FLOAT_FIELD_20_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloatField20());
    hash = (37 * hash) + FIXED32_FIELD_21_FIELD_NUMBER;
    hash = (53 * hash) + getFixed32Field21();
    hash = (37 * hash) + FIXED64_FIELD_22_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFixed64Field22());
    hash = (37 * hash) + SFIXED32_FIELD_23_FIELD_NUMBER;
    hash = (53 * hash) + getSfixed32Field23();
    hash = (37 * hash) + SFIXED64_FIELD_24_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSfixed64Field24());
    hash = (37 * hash) + DOUBLE_FIELD_25_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDoubleField25()));
    hash = (37 * hash) + UINT32_FIELD_26_FIELD_NUMBER;
    hash = (53 * hash) + getUint32Field26();
    hash = (37 * hash) + UINT64_FIELD_27_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUint64Field27());
    hash = (37 * hash) + BOOL_FIELD_28_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolField28());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amstee.flink.formats.proto.test.v1.BigPbMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amstee.flink.formats.proto.test.v1.BigPbMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amstee.flink.formats.proto.test.v1.BigPbMessage)
      com.amstee.flink.formats.proto.test.v1.BigPbMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amstee.flink.formats.proto.test.v1.TestBigProto.internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amstee.flink.formats.proto.test.v1.TestBigProto.internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amstee.flink.formats.proto.test.v1.BigPbMessage.class, com.amstee.flink.formats.proto.test.v1.BigPbMessage.Builder.class);
    }

    // Construct using com.amstee.flink.formats.proto.test.v1.BigPbMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      intField1_ = 0;
      boolField2_ = false;
      stringField3_ = "";
      bytesField4_ = com.google.protobuf.ByteString.EMPTY;
      doubleField5_ = 0D;
      floatField6_ = 0F;
      uint32Field7_ = 0;
      int64Field8_ = 0L;
      uint64Field9_ = 0L;
      bytesField10_ = com.google.protobuf.ByteString.EMPTY;
      doubleField11_ = 0D;
      bytesField12_ = com.google.protobuf.ByteString.EMPTY;
      boolField13_ = false;
      stringField14_ = "";
      floatField15_ = 0F;
      int32Field16_ = 0;
      bytesField17_ = com.google.protobuf.ByteString.EMPTY;
      boolField18_ = false;
      stringField19_ = "";
      floatField20_ = 0F;
      fixed32Field21_ = 0;
      fixed64Field22_ = 0L;
      sfixed32Field23_ = 0;
      sfixed64Field24_ = 0L;
      doubleField25_ = 0D;
      uint32Field26_ = 0;
      uint64Field27_ = 0L;
      boolField28_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amstee.flink.formats.proto.test.v1.TestBigProto.internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_descriptor;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.BigPbMessage getDefaultInstanceForType() {
      return com.amstee.flink.formats.proto.test.v1.BigPbMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.BigPbMessage build() {
      com.amstee.flink.formats.proto.test.v1.BigPbMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.BigPbMessage buildPartial() {
      com.amstee.flink.formats.proto.test.v1.BigPbMessage result = new com.amstee.flink.formats.proto.test.v1.BigPbMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.amstee.flink.formats.proto.test.v1.BigPbMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.intField1_ = intField1_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.boolField2_ = boolField2_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stringField3_ = stringField3_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bytesField4_ = bytesField4_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.doubleField5_ = doubleField5_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.floatField6_ = floatField6_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.uint32Field7_ = uint32Field7_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.int64Field8_ = int64Field8_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.uint64Field9_ = uint64Field9_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.bytesField10_ = bytesField10_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.doubleField11_ = doubleField11_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.bytesField12_ = bytesField12_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.boolField13_ = boolField13_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.stringField14_ = stringField14_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.floatField15_ = floatField15_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.int32Field16_ = int32Field16_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.bytesField17_ = bytesField17_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.boolField18_ = boolField18_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.stringField19_ = stringField19_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.floatField20_ = floatField20_;
      }
      if (((from_bitField0_ & 0x00100000) != 0)) {
        result.fixed32Field21_ = fixed32Field21_;
      }
      if (((from_bitField0_ & 0x00200000) != 0)) {
        result.fixed64Field22_ = fixed64Field22_;
      }
      if (((from_bitField0_ & 0x00400000) != 0)) {
        result.sfixed32Field23_ = sfixed32Field23_;
      }
      if (((from_bitField0_ & 0x00800000) != 0)) {
        result.sfixed64Field24_ = sfixed64Field24_;
      }
      if (((from_bitField0_ & 0x01000000) != 0)) {
        result.doubleField25_ = doubleField25_;
      }
      if (((from_bitField0_ & 0x02000000) != 0)) {
        result.uint32Field26_ = uint32Field26_;
      }
      if (((from_bitField0_ & 0x04000000) != 0)) {
        result.uint64Field27_ = uint64Field27_;
      }
      if (((from_bitField0_ & 0x08000000) != 0)) {
        result.boolField28_ = boolField28_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amstee.flink.formats.proto.test.v1.BigPbMessage) {
        return mergeFrom((com.amstee.flink.formats.proto.test.v1.BigPbMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amstee.flink.formats.proto.test.v1.BigPbMessage other) {
      if (other == com.amstee.flink.formats.proto.test.v1.BigPbMessage.getDefaultInstance()) return this;
      if (other.getIntField1() != 0) {
        setIntField1(other.getIntField1());
      }
      if (other.getBoolField2() != false) {
        setBoolField2(other.getBoolField2());
      }
      if (!other.getStringField3().isEmpty()) {
        stringField3_ = other.stringField3_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getBytesField4() != com.google.protobuf.ByteString.EMPTY) {
        setBytesField4(other.getBytesField4());
      }
      if (other.getDoubleField5() != 0D) {
        setDoubleField5(other.getDoubleField5());
      }
      if (other.getFloatField6() != 0F) {
        setFloatField6(other.getFloatField6());
      }
      if (other.getUint32Field7() != 0) {
        setUint32Field7(other.getUint32Field7());
      }
      if (other.getInt64Field8() != 0L) {
        setInt64Field8(other.getInt64Field8());
      }
      if (other.getUint64Field9() != 0L) {
        setUint64Field9(other.getUint64Field9());
      }
      if (other.getBytesField10() != com.google.protobuf.ByteString.EMPTY) {
        setBytesField10(other.getBytesField10());
      }
      if (other.getDoubleField11() != 0D) {
        setDoubleField11(other.getDoubleField11());
      }
      if (other.getBytesField12() != com.google.protobuf.ByteString.EMPTY) {
        setBytesField12(other.getBytesField12());
      }
      if (other.getBoolField13() != false) {
        setBoolField13(other.getBoolField13());
      }
      if (!other.getStringField14().isEmpty()) {
        stringField14_ = other.stringField14_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (other.getFloatField15() != 0F) {
        setFloatField15(other.getFloatField15());
      }
      if (other.getInt32Field16() != 0) {
        setInt32Field16(other.getInt32Field16());
      }
      if (other.getBytesField17() != com.google.protobuf.ByteString.EMPTY) {
        setBytesField17(other.getBytesField17());
      }
      if (other.getBoolField18() != false) {
        setBoolField18(other.getBoolField18());
      }
      if (!other.getStringField19().isEmpty()) {
        stringField19_ = other.stringField19_;
        bitField0_ |= 0x00040000;
        onChanged();
      }
      if (other.getFloatField20() != 0F) {
        setFloatField20(other.getFloatField20());
      }
      if (other.getFixed32Field21() != 0) {
        setFixed32Field21(other.getFixed32Field21());
      }
      if (other.getFixed64Field22() != 0L) {
        setFixed64Field22(other.getFixed64Field22());
      }
      if (other.getSfixed32Field23() != 0) {
        setSfixed32Field23(other.getSfixed32Field23());
      }
      if (other.getSfixed64Field24() != 0L) {
        setSfixed64Field24(other.getSfixed64Field24());
      }
      if (other.getDoubleField25() != 0D) {
        setDoubleField25(other.getDoubleField25());
      }
      if (other.getUint32Field26() != 0) {
        setUint32Field26(other.getUint32Field26());
      }
      if (other.getUint64Field27() != 0L) {
        setUint64Field27(other.getUint64Field27());
      }
      if (other.getBoolField28() != false) {
        setBoolField28(other.getBoolField28());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              intField1_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              boolField2_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              stringField3_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              bytesField4_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 41: {
              doubleField5_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 53: {
              floatField6_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 56: {
              uint32Field7_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              int64Field8_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              uint64Field9_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              bytesField10_ = input.readBytes();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 89: {
              doubleField11_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 98: {
              bytesField12_ = input.readBytes();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 104: {
              boolField13_ = input.readBool();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 114: {
              stringField14_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 125: {
              floatField15_ = input.readFloat();
              bitField0_ |= 0x00004000;
              break;
            } // case 125
            case 128: {
              int32Field16_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            case 138: {
              bytesField17_ = input.readBytes();
              bitField0_ |= 0x00010000;
              break;
            } // case 138
            case 144: {
              boolField18_ = input.readBool();
              bitField0_ |= 0x00020000;
              break;
            } // case 144
            case 154: {
              stringField19_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00040000;
              break;
            } // case 154
            case 165: {
              floatField20_ = input.readFloat();
              bitField0_ |= 0x00080000;
              break;
            } // case 165
            case 173: {
              fixed32Field21_ = input.readFixed32();
              bitField0_ |= 0x00100000;
              break;
            } // case 173
            case 177: {
              fixed64Field22_ = input.readFixed64();
              bitField0_ |= 0x00200000;
              break;
            } // case 177
            case 189: {
              sfixed32Field23_ = input.readSFixed32();
              bitField0_ |= 0x00400000;
              break;
            } // case 189
            case 193: {
              sfixed64Field24_ = input.readSFixed64();
              bitField0_ |= 0x00800000;
              break;
            } // case 193
            case 201: {
              doubleField25_ = input.readDouble();
              bitField0_ |= 0x01000000;
              break;
            } // case 201
            case 208: {
              uint32Field26_ = input.readUInt32();
              bitField0_ |= 0x02000000;
              break;
            } // case 208
            case 216: {
              uint64Field27_ = input.readUInt64();
              bitField0_ |= 0x04000000;
              break;
            } // case 216
            case 224: {
              boolField28_ = input.readBool();
              bitField0_ |= 0x08000000;
              break;
            } // case 224
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int intField1_ ;
    /**
     * <code>int32 int_field_1 = 1 [json_name = "intField1"];</code>
     * @return The intField1.
     */
    @java.lang.Override
    public int getIntField1() {
      return intField1_;
    }
    /**
     * <code>int32 int_field_1 = 1 [json_name = "intField1"];</code>
     * @param value The intField1 to set.
     * @return This builder for chaining.
     */
    public Builder setIntField1(int value) {

      intField1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int_field_1 = 1 [json_name = "intField1"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIntField1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      intField1_ = 0;
      onChanged();
      return this;
    }

    private boolean boolField2_ ;
    /**
     * <code>bool bool_field_2 = 2 [json_name = "boolField2"];</code>
     * @return The boolField2.
     */
    @java.lang.Override
    public boolean getBoolField2() {
      return boolField2_;
    }
    /**
     * <code>bool bool_field_2 = 2 [json_name = "boolField2"];</code>
     * @param value The boolField2 to set.
     * @return This builder for chaining.
     */
    public Builder setBoolField2(boolean value) {

      boolField2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_field_2 = 2 [json_name = "boolField2"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolField2() {
      bitField0_ = (bitField0_ & ~0x00000002);
      boolField2_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object stringField3_ = "";
    /**
     * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
     * @return The stringField3.
     */
    public java.lang.String getStringField3() {
      java.lang.Object ref = stringField3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringField3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
     * @return The bytes for stringField3.
     */
    public com.google.protobuf.ByteString
        getStringField3Bytes() {
      java.lang.Object ref = stringField3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
     * @param value The stringField3 to set.
     * @return This builder for chaining.
     */
    public Builder setStringField3(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stringField3_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStringField3() {
      stringField3_ = getDefaultInstance().getStringField3();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
     * @param value The bytes for stringField3 to set.
     * @return This builder for chaining.
     */
    public Builder setStringField3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stringField3_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytesField4_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes_field_4 = 4 [json_name = "bytesField4"];</code>
     * @return The bytesField4.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesField4() {
      return bytesField4_;
    }
    /**
     * <code>bytes bytes_field_4 = 4 [json_name = "bytesField4"];</code>
     * @param value The bytesField4 to set.
     * @return This builder for chaining.
     */
    public Builder setBytesField4(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      bytesField4_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes_field_4 = 4 [json_name = "bytesField4"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesField4() {
      bitField0_ = (bitField0_ & ~0x00000008);
      bytesField4_ = getDefaultInstance().getBytesField4();
      onChanged();
      return this;
    }

    private double doubleField5_ ;
    /**
     * <code>double double_field_5 = 5 [json_name = "doubleField5"];</code>
     * @return The doubleField5.
     */
    @java.lang.Override
    public double getDoubleField5() {
      return doubleField5_;
    }
    /**
     * <code>double double_field_5 = 5 [json_name = "doubleField5"];</code>
     * @param value The doubleField5 to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleField5(double value) {

      doubleField5_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double double_field_5 = 5 [json_name = "doubleField5"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleField5() {
      bitField0_ = (bitField0_ & ~0x00000010);
      doubleField5_ = 0D;
      onChanged();
      return this;
    }

    private float floatField6_ ;
    /**
     * <code>float float_field_6 = 6 [json_name = "floatField6"];</code>
     * @return The floatField6.
     */
    @java.lang.Override
    public float getFloatField6() {
      return floatField6_;
    }
    /**
     * <code>float float_field_6 = 6 [json_name = "floatField6"];</code>
     * @param value The floatField6 to set.
     * @return This builder for chaining.
     */
    public Builder setFloatField6(float value) {

      floatField6_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float float_field_6 = 6 [json_name = "floatField6"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatField6() {
      bitField0_ = (bitField0_ & ~0x00000020);
      floatField6_ = 0F;
      onChanged();
      return this;
    }

    private int uint32Field7_ ;
    /**
     * <code>uint32 uint32_field_7 = 7 [json_name = "uint32Field7"];</code>
     * @return The uint32Field7.
     */
    @java.lang.Override
    public int getUint32Field7() {
      return uint32Field7_;
    }
    /**
     * <code>uint32 uint32_field_7 = 7 [json_name = "uint32Field7"];</code>
     * @param value The uint32Field7 to set.
     * @return This builder for chaining.
     */
    public Builder setUint32Field7(int value) {

      uint32Field7_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uint32_field_7 = 7 [json_name = "uint32Field7"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32Field7() {
      bitField0_ = (bitField0_ & ~0x00000040);
      uint32Field7_ = 0;
      onChanged();
      return this;
    }

    private long int64Field8_ ;
    /**
     * <code>int64 int64_field_8 = 8 [json_name = "int64Field8"];</code>
     * @return The int64Field8.
     */
    @java.lang.Override
    public long getInt64Field8() {
      return int64Field8_;
    }
    /**
     * <code>int64 int64_field_8 = 8 [json_name = "int64Field8"];</code>
     * @param value The int64Field8 to set.
     * @return This builder for chaining.
     */
    public Builder setInt64Field8(long value) {

      int64Field8_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 int64_field_8 = 8 [json_name = "int64Field8"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64Field8() {
      bitField0_ = (bitField0_ & ~0x00000080);
      int64Field8_ = 0L;
      onChanged();
      return this;
    }

    private long uint64Field9_ ;
    /**
     * <code>uint64 uint64_field_9 = 9 [json_name = "uint64Field9"];</code>
     * @return The uint64Field9.
     */
    @java.lang.Override
    public long getUint64Field9() {
      return uint64Field9_;
    }
    /**
     * <code>uint64 uint64_field_9 = 9 [json_name = "uint64Field9"];</code>
     * @param value The uint64Field9 to set.
     * @return This builder for chaining.
     */
    public Builder setUint64Field9(long value) {

      uint64Field9_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64_field_9 = 9 [json_name = "uint64Field9"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64Field9() {
      bitField0_ = (bitField0_ & ~0x00000100);
      uint64Field9_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytesField10_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes_field_10 = 10 [json_name = "bytesField10"];</code>
     * @return The bytesField10.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesField10() {
      return bytesField10_;
    }
    /**
     * <code>bytes bytes_field_10 = 10 [json_name = "bytesField10"];</code>
     * @param value The bytesField10 to set.
     * @return This builder for chaining.
     */
    public Builder setBytesField10(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      bytesField10_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes_field_10 = 10 [json_name = "bytesField10"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesField10() {
      bitField0_ = (bitField0_ & ~0x00000200);
      bytesField10_ = getDefaultInstance().getBytesField10();
      onChanged();
      return this;
    }

    private double doubleField11_ ;
    /**
     * <code>double double_field_11 = 11 [json_name = "doubleField11"];</code>
     * @return The doubleField11.
     */
    @java.lang.Override
    public double getDoubleField11() {
      return doubleField11_;
    }
    /**
     * <code>double double_field_11 = 11 [json_name = "doubleField11"];</code>
     * @param value The doubleField11 to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleField11(double value) {

      doubleField11_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>double double_field_11 = 11 [json_name = "doubleField11"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleField11() {
      bitField0_ = (bitField0_ & ~0x00000400);
      doubleField11_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytesField12_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes_field_12 = 12 [json_name = "bytesField12"];</code>
     * @return The bytesField12.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesField12() {
      return bytesField12_;
    }
    /**
     * <code>bytes bytes_field_12 = 12 [json_name = "bytesField12"];</code>
     * @param value The bytesField12 to set.
     * @return This builder for chaining.
     */
    public Builder setBytesField12(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      bytesField12_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes_field_12 = 12 [json_name = "bytesField12"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesField12() {
      bitField0_ = (bitField0_ & ~0x00000800);
      bytesField12_ = getDefaultInstance().getBytesField12();
      onChanged();
      return this;
    }

    private boolean boolField13_ ;
    /**
     * <code>bool bool_field_13 = 13 [json_name = "boolField13"];</code>
     * @return The boolField13.
     */
    @java.lang.Override
    public boolean getBoolField13() {
      return boolField13_;
    }
    /**
     * <code>bool bool_field_13 = 13 [json_name = "boolField13"];</code>
     * @param value The boolField13 to set.
     * @return This builder for chaining.
     */
    public Builder setBoolField13(boolean value) {

      boolField13_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_field_13 = 13 [json_name = "boolField13"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolField13() {
      bitField0_ = (bitField0_ & ~0x00001000);
      boolField13_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object stringField14_ = "";
    /**
     * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
     * @return The stringField14.
     */
    public java.lang.String getStringField14() {
      java.lang.Object ref = stringField14_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringField14_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
     * @return The bytes for stringField14.
     */
    public com.google.protobuf.ByteString
        getStringField14Bytes() {
      java.lang.Object ref = stringField14_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField14_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
     * @param value The stringField14 to set.
     * @return This builder for chaining.
     */
    public Builder setStringField14(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stringField14_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStringField14() {
      stringField14_ = getDefaultInstance().getStringField14();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
     * @param value The bytes for stringField14 to set.
     * @return This builder for chaining.
     */
    public Builder setStringField14Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stringField14_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private float floatField15_ ;
    /**
     * <code>float float_field_15 = 15 [json_name = "floatField15"];</code>
     * @return The floatField15.
     */
    @java.lang.Override
    public float getFloatField15() {
      return floatField15_;
    }
    /**
     * <code>float float_field_15 = 15 [json_name = "floatField15"];</code>
     * @param value The floatField15 to set.
     * @return This builder for chaining.
     */
    public Builder setFloatField15(float value) {

      floatField15_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>float float_field_15 = 15 [json_name = "floatField15"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatField15() {
      bitField0_ = (bitField0_ & ~0x00004000);
      floatField15_ = 0F;
      onChanged();
      return this;
    }

    private int int32Field16_ ;
    /**
     * <code>int32 int32_field_16 = 16 [json_name = "int32Field16"];</code>
     * @return The int32Field16.
     */
    @java.lang.Override
    public int getInt32Field16() {
      return int32Field16_;
    }
    /**
     * <code>int32 int32_field_16 = 16 [json_name = "int32Field16"];</code>
     * @param value The int32Field16 to set.
     * @return This builder for chaining.
     */
    public Builder setInt32Field16(int value) {

      int32Field16_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int32_field_16 = 16 [json_name = "int32Field16"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInt32Field16() {
      bitField0_ = (bitField0_ & ~0x00008000);
      int32Field16_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytesField17_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes_field_17 = 17 [json_name = "bytesField17"];</code>
     * @return The bytesField17.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesField17() {
      return bytesField17_;
    }
    /**
     * <code>bytes bytes_field_17 = 17 [json_name = "bytesField17"];</code>
     * @param value The bytesField17 to set.
     * @return This builder for chaining.
     */
    public Builder setBytesField17(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      bytesField17_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes_field_17 = 17 [json_name = "bytesField17"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesField17() {
      bitField0_ = (bitField0_ & ~0x00010000);
      bytesField17_ = getDefaultInstance().getBytesField17();
      onChanged();
      return this;
    }

    private boolean boolField18_ ;
    /**
     * <code>bool bool_field_18 = 18 [json_name = "boolField18"];</code>
     * @return The boolField18.
     */
    @java.lang.Override
    public boolean getBoolField18() {
      return boolField18_;
    }
    /**
     * <code>bool bool_field_18 = 18 [json_name = "boolField18"];</code>
     * @param value The boolField18 to set.
     * @return This builder for chaining.
     */
    public Builder setBoolField18(boolean value) {

      boolField18_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_field_18 = 18 [json_name = "boolField18"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolField18() {
      bitField0_ = (bitField0_ & ~0x00020000);
      boolField18_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object stringField19_ = "";
    /**
     * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
     * @return The stringField19.
     */
    public java.lang.String getStringField19() {
      java.lang.Object ref = stringField19_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringField19_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
     * @return The bytes for stringField19.
     */
    public com.google.protobuf.ByteString
        getStringField19Bytes() {
      java.lang.Object ref = stringField19_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField19_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
     * @param value The stringField19 to set.
     * @return This builder for chaining.
     */
    public Builder setStringField19(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stringField19_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStringField19() {
      stringField19_ = getDefaultInstance().getStringField19();
      bitField0_ = (bitField0_ & ~0x00040000);
      onChanged();
      return this;
    }
    /**
     * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
     * @param value The bytes for stringField19 to set.
     * @return This builder for chaining.
     */
    public Builder setStringField19Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stringField19_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }

    private float floatField20_ ;
    /**
     * <code>float float_field_20 = 20 [json_name = "floatField20"];</code>
     * @return The floatField20.
     */
    @java.lang.Override
    public float getFloatField20() {
      return floatField20_;
    }
    /**
     * <code>float float_field_20 = 20 [json_name = "floatField20"];</code>
     * @param value The floatField20 to set.
     * @return This builder for chaining.
     */
    public Builder setFloatField20(float value) {

      floatField20_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <code>float float_field_20 = 20 [json_name = "floatField20"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatField20() {
      bitField0_ = (bitField0_ & ~0x00080000);
      floatField20_ = 0F;
      onChanged();
      return this;
    }

    private int fixed32Field21_ ;
    /**
     * <code>fixed32 fixed32_field_21 = 21 [json_name = "fixed32Field21"];</code>
     * @return The fixed32Field21.
     */
    @java.lang.Override
    public int getFixed32Field21() {
      return fixed32Field21_;
    }
    /**
     * <code>fixed32 fixed32_field_21 = 21 [json_name = "fixed32Field21"];</code>
     * @param value The fixed32Field21 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed32Field21(int value) {

      fixed32Field21_ = value;
      bitField0_ |= 0x00100000;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 fixed32_field_21 = 21 [json_name = "fixed32Field21"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed32Field21() {
      bitField0_ = (bitField0_ & ~0x00100000);
      fixed32Field21_ = 0;
      onChanged();
      return this;
    }

    private long fixed64Field22_ ;
    /**
     * <code>fixed64 fixed64_field_22 = 22 [json_name = "fixed64Field22"];</code>
     * @return The fixed64Field22.
     */
    @java.lang.Override
    public long getFixed64Field22() {
      return fixed64Field22_;
    }
    /**
     * <code>fixed64 fixed64_field_22 = 22 [json_name = "fixed64Field22"];</code>
     * @param value The fixed64Field22 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed64Field22(long value) {

      fixed64Field22_ = value;
      bitField0_ |= 0x00200000;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 fixed64_field_22 = 22 [json_name = "fixed64Field22"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed64Field22() {
      bitField0_ = (bitField0_ & ~0x00200000);
      fixed64Field22_ = 0L;
      onChanged();
      return this;
    }

    private int sfixed32Field23_ ;
    /**
     * <code>sfixed32 sfixed32_field_23 = 23 [json_name = "sfixed32Field23"];</code>
     * @return The sfixed32Field23.
     */
    @java.lang.Override
    public int getSfixed32Field23() {
      return sfixed32Field23_;
    }
    /**
     * <code>sfixed32 sfixed32_field_23 = 23 [json_name = "sfixed32Field23"];</code>
     * @param value The sfixed32Field23 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed32Field23(int value) {

      sfixed32Field23_ = value;
      bitField0_ |= 0x00400000;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed32 sfixed32_field_23 = 23 [json_name = "sfixed32Field23"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed32Field23() {
      bitField0_ = (bitField0_ & ~0x00400000);
      sfixed32Field23_ = 0;
      onChanged();
      return this;
    }

    private long sfixed64Field24_ ;
    /**
     * <code>sfixed64 sfixed64_field_24 = 24 [json_name = "sfixed64Field24"];</code>
     * @return The sfixed64Field24.
     */
    @java.lang.Override
    public long getSfixed64Field24() {
      return sfixed64Field24_;
    }
    /**
     * <code>sfixed64 sfixed64_field_24 = 24 [json_name = "sfixed64Field24"];</code>
     * @param value The sfixed64Field24 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed64Field24(long value) {

      sfixed64Field24_ = value;
      bitField0_ |= 0x00800000;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed64 sfixed64_field_24 = 24 [json_name = "sfixed64Field24"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed64Field24() {
      bitField0_ = (bitField0_ & ~0x00800000);
      sfixed64Field24_ = 0L;
      onChanged();
      return this;
    }

    private double doubleField25_ ;
    /**
     * <code>double double_field_25 = 25 [json_name = "doubleField25"];</code>
     * @return The doubleField25.
     */
    @java.lang.Override
    public double getDoubleField25() {
      return doubleField25_;
    }
    /**
     * <code>double double_field_25 = 25 [json_name = "doubleField25"];</code>
     * @param value The doubleField25 to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleField25(double value) {

      doubleField25_ = value;
      bitField0_ |= 0x01000000;
      onChanged();
      return this;
    }
    /**
     * <code>double double_field_25 = 25 [json_name = "doubleField25"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleField25() {
      bitField0_ = (bitField0_ & ~0x01000000);
      doubleField25_ = 0D;
      onChanged();
      return this;
    }

    private int uint32Field26_ ;
    /**
     * <code>uint32 uint32_field_26 = 26 [json_name = "uint32Field26"];</code>
     * @return The uint32Field26.
     */
    @java.lang.Override
    public int getUint32Field26() {
      return uint32Field26_;
    }
    /**
     * <code>uint32 uint32_field_26 = 26 [json_name = "uint32Field26"];</code>
     * @param value The uint32Field26 to set.
     * @return This builder for chaining.
     */
    public Builder setUint32Field26(int value) {

      uint32Field26_ = value;
      bitField0_ |= 0x02000000;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uint32_field_26 = 26 [json_name = "uint32Field26"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32Field26() {
      bitField0_ = (bitField0_ & ~0x02000000);
      uint32Field26_ = 0;
      onChanged();
      return this;
    }

    private long uint64Field27_ ;
    /**
     * <code>uint64 uint64_field_27 = 27 [json_name = "uint64Field27"];</code>
     * @return The uint64Field27.
     */
    @java.lang.Override
    public long getUint64Field27() {
      return uint64Field27_;
    }
    /**
     * <code>uint64 uint64_field_27 = 27 [json_name = "uint64Field27"];</code>
     * @param value The uint64Field27 to set.
     * @return This builder for chaining.
     */
    public Builder setUint64Field27(long value) {

      uint64Field27_ = value;
      bitField0_ |= 0x04000000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64_field_27 = 27 [json_name = "uint64Field27"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64Field27() {
      bitField0_ = (bitField0_ & ~0x04000000);
      uint64Field27_ = 0L;
      onChanged();
      return this;
    }

    private boolean boolField28_ ;
    /**
     * <code>bool bool_field_28 = 28 [json_name = "boolField28"];</code>
     * @return The boolField28.
     */
    @java.lang.Override
    public boolean getBoolField28() {
      return boolField28_;
    }
    /**
     * <code>bool bool_field_28 = 28 [json_name = "boolField28"];</code>
     * @param value The boolField28 to set.
     * @return This builder for chaining.
     */
    public Builder setBoolField28(boolean value) {

      boolField28_ = value;
      bitField0_ |= 0x08000000;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_field_28 = 28 [json_name = "boolField28"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolField28() {
      bitField0_ = (bitField0_ & ~0x08000000);
      boolField28_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amstee.flink.formats.proto.test.v1.BigPbMessage)
  }

  // @@protoc_insertion_point(class_scope:amstee.flink.formats.proto.test.v1.BigPbMessage)
  private static final com.amstee.flink.formats.proto.test.v1.BigPbMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amstee.flink.formats.proto.test.v1.BigPbMessage();
  }

  public static com.amstee.flink.formats.proto.test.v1.BigPbMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BigPbMessage>
      PARSER = new com.google.protobuf.AbstractParser<BigPbMessage>() {
    @java.lang.Override
    public BigPbMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BigPbMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BigPbMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.BigPbMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

