// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_big.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public interface BigPbMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amstee.flink.formats.proto.test.v1.BigPbMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 int_field_1 = 1 [json_name = "intField1"];</code>
   * @return The intField1.
   */
  int getIntField1();

  /**
   * <code>bool bool_field_2 = 2 [json_name = "boolField2"];</code>
   * @return The boolField2.
   */
  boolean getBoolField2();

  /**
   * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
   * @return The stringField3.
   */
  java.lang.String getStringField3();
  /**
   * <code>string string_field_3 = 3 [json_name = "stringField3"];</code>
   * @return The bytes for stringField3.
   */
  com.google.protobuf.ByteString
      getStringField3Bytes();

  /**
   * <code>bytes bytes_field_4 = 4 [json_name = "bytesField4"];</code>
   * @return The bytesField4.
   */
  com.google.protobuf.ByteString getBytesField4();

  /**
   * <code>double double_field_5 = 5 [json_name = "doubleField5"];</code>
   * @return The doubleField5.
   */
  double getDoubleField5();

  /**
   * <code>float float_field_6 = 6 [json_name = "floatField6"];</code>
   * @return The floatField6.
   */
  float getFloatField6();

  /**
   * <code>uint32 uint32_field_7 = 7 [json_name = "uint32Field7"];</code>
   * @return The uint32Field7.
   */
  int getUint32Field7();

  /**
   * <code>int64 int64_field_8 = 8 [json_name = "int64Field8"];</code>
   * @return The int64Field8.
   */
  long getInt64Field8();

  /**
   * <code>uint64 uint64_field_9 = 9 [json_name = "uint64Field9"];</code>
   * @return The uint64Field9.
   */
  long getUint64Field9();

  /**
   * <code>bytes bytes_field_10 = 10 [json_name = "bytesField10"];</code>
   * @return The bytesField10.
   */
  com.google.protobuf.ByteString getBytesField10();

  /**
   * <code>double double_field_11 = 11 [json_name = "doubleField11"];</code>
   * @return The doubleField11.
   */
  double getDoubleField11();

  /**
   * <code>bytes bytes_field_12 = 12 [json_name = "bytesField12"];</code>
   * @return The bytesField12.
   */
  com.google.protobuf.ByteString getBytesField12();

  /**
   * <code>bool bool_field_13 = 13 [json_name = "boolField13"];</code>
   * @return The boolField13.
   */
  boolean getBoolField13();

  /**
   * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
   * @return The stringField14.
   */
  java.lang.String getStringField14();
  /**
   * <code>string string_field_14 = 14 [json_name = "stringField14"];</code>
   * @return The bytes for stringField14.
   */
  com.google.protobuf.ByteString
      getStringField14Bytes();

  /**
   * <code>float float_field_15 = 15 [json_name = "floatField15"];</code>
   * @return The floatField15.
   */
  float getFloatField15();

  /**
   * <code>int32 int32_field_16 = 16 [json_name = "int32Field16"];</code>
   * @return The int32Field16.
   */
  int getInt32Field16();

  /**
   * <code>bytes bytes_field_17 = 17 [json_name = "bytesField17"];</code>
   * @return The bytesField17.
   */
  com.google.protobuf.ByteString getBytesField17();

  /**
   * <code>bool bool_field_18 = 18 [json_name = "boolField18"];</code>
   * @return The boolField18.
   */
  boolean getBoolField18();

  /**
   * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
   * @return The stringField19.
   */
  java.lang.String getStringField19();
  /**
   * <code>string string_field_19 = 19 [json_name = "stringField19"];</code>
   * @return The bytes for stringField19.
   */
  com.google.protobuf.ByteString
      getStringField19Bytes();

  /**
   * <code>float float_field_20 = 20 [json_name = "floatField20"];</code>
   * @return The floatField20.
   */
  float getFloatField20();

  /**
   * <code>fixed32 fixed32_field_21 = 21 [json_name = "fixed32Field21"];</code>
   * @return The fixed32Field21.
   */
  int getFixed32Field21();

  /**
   * <code>fixed64 fixed64_field_22 = 22 [json_name = "fixed64Field22"];</code>
   * @return The fixed64Field22.
   */
  long getFixed64Field22();

  /**
   * <code>sfixed32 sfixed32_field_23 = 23 [json_name = "sfixed32Field23"];</code>
   * @return The sfixed32Field23.
   */
  int getSfixed32Field23();

  /**
   * <code>sfixed64 sfixed64_field_24 = 24 [json_name = "sfixed64Field24"];</code>
   * @return The sfixed64Field24.
   */
  long getSfixed64Field24();

  /**
   * <code>double double_field_25 = 25 [json_name = "doubleField25"];</code>
   * @return The doubleField25.
   */
  double getDoubleField25();

  /**
   * <code>uint32 uint32_field_26 = 26 [json_name = "uint32Field26"];</code>
   * @return The uint32Field26.
   */
  int getUint32Field26();

  /**
   * <code>uint64 uint64_field_27 = 27 [json_name = "uint64Field27"];</code>
   * @return The uint64Field27.
   */
  long getUint64Field27();

  /**
   * <code>bool bool_field_28 = 28 [json_name = "boolField28"];</code>
   * @return The boolField28.
   */
  boolean getBoolField28();
}
