// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_map.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public interface MapTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amstee.flink.formats.proto.test.v1.MapTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
   */
  int getSimpleStringMapCount();
  /**
   * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
   */
  boolean containsSimpleStringMap(
      java.lang.String key);
  /**
   * Use {@link #getSimpleStringMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getSimpleStringMap();
  /**
   * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getSimpleStringMapMap();
  /**
   * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
   */
  /* nullable */
java.lang.String getSimpleStringMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
   */
  java.lang.String getSimpleStringMapOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
   */
  int getNestedMapCount();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
   */
  boolean containsNestedMap(
      java.lang.String key);
  /**
   * Use {@link #getNestedMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.amstee.flink.formats.proto.test.v1.NestedMap>
  getNestedMap();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
   */
  java.util.Map<java.lang.String, com.amstee.flink.formats.proto.test.v1.NestedMap>
  getNestedMapMap();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
   */
  /* nullable */
com.amstee.flink.formats.proto.test.v1.NestedMap getNestedMapOrDefault(
      java.lang.String key,
      /* nullable */
com.amstee.flink.formats.proto.test.v1.NestedMap defaultValue);
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
   */
  com.amstee.flink.formats.proto.test.v1.NestedMap getNestedMapOrThrow(
      java.lang.String key);
}
