// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_map.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public interface NestedMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amstee.flink.formats.proto.test.v1.NestedMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
