// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_repeated.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

/**
 * Protobuf type {@code amstee.flink.formats.proto.test.v1.RepeatedTest}
 */
public final class RepeatedTest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amstee.flink.formats.proto.test.v1.RepeatedTest)
    RepeatedTestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RepeatedTest.newBuilder() to construct.
  private RepeatedTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepeatedTest() {
    values_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    numbers_ = emptyIntList();
    floats_ = emptyFloatList();
    doubles_ = emptyDoubleList();
    bools_ = emptyBooleanList();
    bytes_ = emptyList(com.google.protobuf.ByteString.class);
    stringValues_ = java.util.Collections.emptyList();
    timestamps_ = java.util.Collections.emptyList();
    nestedRepeated_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RepeatedTest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amstee.flink.formats.proto.test.v1.TestRepeatedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amstee.flink.formats.proto.test.v1.TestRepeatedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amstee.flink.formats.proto.test.v1.RepeatedTest.class, com.amstee.flink.formats.proto.test.v1.RepeatedTest.Builder.class);
  }

  public static final int VALUES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList values_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string values = 1 [json_name = "values"];</code>
   * @return A list containing the values.
   */
  public com.google.protobuf.ProtocolStringList
      getValuesList() {
    return values_;
  }
  /**
   * <code>repeated string values = 1 [json_name = "values"];</code>
   * @return The count of values.
   */
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <code>repeated string values = 1 [json_name = "values"];</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  public java.lang.String getValues(int index) {
    return values_.get(index);
  }
  /**
   * <code>repeated string values = 1 [json_name = "values"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the values at the given index.
   */
  public com.google.protobuf.ByteString
      getValuesBytes(int index) {
    return values_.getByteString(index);
  }

  public static final int NUMBERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList numbers_ =
      emptyIntList();
  /**
   * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
   * @return A list containing the numbers.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getNumbersList() {
    return numbers_;
  }
  /**
   * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
   * @return The count of numbers.
   */
  public int getNumbersCount() {
    return numbers_.size();
  }
  /**
   * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
   * @param index The index of the element to return.
   * @return The numbers at the given index.
   */
  public int getNumbers(int index) {
    return numbers_.getInt(index);
  }
  private int numbersMemoizedSerializedSize = -1;

  public static final int FLOATS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList floats_ =
      emptyFloatList();
  /**
   * <code>repeated float floats = 3 [json_name = "floats"];</code>
   * @return A list containing the floats.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getFloatsList() {
    return floats_;
  }
  /**
   * <code>repeated float floats = 3 [json_name = "floats"];</code>
   * @return The count of floats.
   */
  public int getFloatsCount() {
    return floats_.size();
  }
  /**
   * <code>repeated float floats = 3 [json_name = "floats"];</code>
   * @param index The index of the element to return.
   * @return The floats at the given index.
   */
  public float getFloats(int index) {
    return floats_.getFloat(index);
  }
  private int floatsMemoizedSerializedSize = -1;

  public static final int DOUBLES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList doubles_ =
      emptyDoubleList();
  /**
   * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
   * @return A list containing the doubles.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getDoublesList() {
    return doubles_;
  }
  /**
   * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
   * @return The count of doubles.
   */
  public int getDoublesCount() {
    return doubles_.size();
  }
  /**
   * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
   * @param index The index of the element to return.
   * @return The doubles at the given index.
   */
  public double getDoubles(int index) {
    return doubles_.getDouble(index);
  }
  private int doublesMemoizedSerializedSize = -1;

  public static final int BOOLS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.BooleanList bools_ =
      emptyBooleanList();
  /**
   * <code>repeated bool bools = 5 [json_name = "bools"];</code>
   * @return A list containing the bools.
   */
  @java.lang.Override
  public java.util.List<java.lang.Boolean>
      getBoolsList() {
    return bools_;
  }
  /**
   * <code>repeated bool bools = 5 [json_name = "bools"];</code>
   * @return The count of bools.
   */
  public int getBoolsCount() {
    return bools_.size();
  }
  /**
   * <code>repeated bool bools = 5 [json_name = "bools"];</code>
   * @param index The index of the element to return.
   * @return The bools at the given index.
   */
  public boolean getBools(int index) {
    return bools_.getBoolean(index);
  }
  private int boolsMemoizedSerializedSize = -1;

  public static final int BYTES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> bytes_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
   * @return A list containing the bytes.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getBytesList() {
    return bytes_;
  }
  /**
   * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
   * @return The count of bytes.
   */
  public int getBytesCount() {
    return bytes_.size();
  }
  /**
   * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
   * @param index The index of the element to return.
   * @return The bytes at the given index.
   */
  public com.google.protobuf.ByteString getBytes(int index) {
    return bytes_.get(index);
  }

  public static final int STRING_VALUES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.StringValue> stringValues_;
  /**
   * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.StringValue> getStringValuesList() {
    return stringValues_;
  }
  /**
   * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.StringValueOrBuilder> 
      getStringValuesOrBuilderList() {
    return stringValues_;
  }
  /**
   * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
   */
  @java.lang.Override
  public int getStringValuesCount() {
    return stringValues_.size();
  }
  /**
   * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getStringValues(int index) {
    return stringValues_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getStringValuesOrBuilder(
      int index) {
    return stringValues_.get(index);
  }

  public static final int TIMESTAMPS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Timestamp> timestamps_;
  /**
   * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Timestamp> getTimestampsList() {
    return timestamps_;
  }
  /**
   * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
      getTimestampsOrBuilderList() {
    return timestamps_;
  }
  /**
   * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
   */
  @java.lang.Override
  public int getTimestampsCount() {
    return timestamps_.size();
  }
  /**
   * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamps(int index) {
    return timestamps_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampsOrBuilder(
      int index) {
    return timestamps_.get(index);
  }

  public static final int NESTED_REPEATED_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<com.amstee.flink.formats.proto.test.v1.NestedRepeated> nestedRepeated_;
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
   */
  @java.lang.Override
  public java.util.List<com.amstee.flink.formats.proto.test.v1.NestedRepeated> getNestedRepeatedList() {
    return nestedRepeated_;
  }
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder> 
      getNestedRepeatedOrBuilderList() {
    return nestedRepeated_;
  }
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
   */
  @java.lang.Override
  public int getNestedRepeatedCount() {
    return nestedRepeated_.size();
  }
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
   */
  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.NestedRepeated getNestedRepeated(int index) {
    return nestedRepeated_.get(index);
  }
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
   */
  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder getNestedRepeatedOrBuilder(
      int index) {
    return nestedRepeated_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < values_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, values_.getRaw(i));
    }
    if (getNumbersList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(numbersMemoizedSerializedSize);
    }
    for (int i = 0; i < numbers_.size(); i++) {
      output.writeInt32NoTag(numbers_.getInt(i));
    }
    if (getFloatsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(floatsMemoizedSerializedSize);
    }
    for (int i = 0; i < floats_.size(); i++) {
      output.writeFloatNoTag(floats_.getFloat(i));
    }
    if (getDoublesList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(doublesMemoizedSerializedSize);
    }
    for (int i = 0; i < doubles_.size(); i++) {
      output.writeDoubleNoTag(doubles_.getDouble(i));
    }
    if (getBoolsList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(boolsMemoizedSerializedSize);
    }
    for (int i = 0; i < bools_.size(); i++) {
      output.writeBoolNoTag(bools_.getBoolean(i));
    }
    for (int i = 0; i < bytes_.size(); i++) {
      output.writeBytes(6, bytes_.get(i));
    }
    for (int i = 0; i < stringValues_.size(); i++) {
      output.writeMessage(7, stringValues_.get(i));
    }
    for (int i = 0; i < timestamps_.size(); i++) {
      output.writeMessage(8, timestamps_.get(i));
    }
    for (int i = 0; i < nestedRepeated_.size(); i++) {
      output.writeMessage(9, nestedRepeated_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < values_.size(); i++) {
        dataSize += computeStringSizeNoTag(values_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getValuesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < numbers_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(numbers_.getInt(i));
      }
      size += dataSize;
      if (!getNumbersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      numbersMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 4 * getFloatsList().size();
      size += dataSize;
      if (!getFloatsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      floatsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 8 * getDoublesList().size();
      size += dataSize;
      if (!getDoublesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      doublesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 1 * getBoolsList().size();
      size += dataSize;
      if (!getBoolsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      boolsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < bytes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(bytes_.get(i));
      }
      size += dataSize;
      size += 1 * getBytesList().size();
    }
    for (int i = 0; i < stringValues_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, stringValues_.get(i));
    }
    for (int i = 0; i < timestamps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, timestamps_.get(i));
    }
    for (int i = 0; i < nestedRepeated_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, nestedRepeated_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amstee.flink.formats.proto.test.v1.RepeatedTest)) {
      return super.equals(obj);
    }
    com.amstee.flink.formats.proto.test.v1.RepeatedTest other = (com.amstee.flink.formats.proto.test.v1.RepeatedTest) obj;

    if (!getValuesList()
        .equals(other.getValuesList())) return false;
    if (!getNumbersList()
        .equals(other.getNumbersList())) return false;
    if (!getFloatsList()
        .equals(other.getFloatsList())) return false;
    if (!getDoublesList()
        .equals(other.getDoublesList())) return false;
    if (!getBoolsList()
        .equals(other.getBoolsList())) return false;
    if (!getBytesList()
        .equals(other.getBytesList())) return false;
    if (!getStringValuesList()
        .equals(other.getStringValuesList())) return false;
    if (!getTimestampsList()
        .equals(other.getTimestampsList())) return false;
    if (!getNestedRepeatedList()
        .equals(other.getNestedRepeatedList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    if (getNumbersCount() > 0) {
      hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getNumbersList().hashCode();
    }
    if (getFloatsCount() > 0) {
      hash = (37 * hash) + FLOATS_FIELD_NUMBER;
      hash = (53 * hash) + getFloatsList().hashCode();
    }
    if (getDoublesCount() > 0) {
      hash = (37 * hash) + DOUBLES_FIELD_NUMBER;
      hash = (53 * hash) + getDoublesList().hashCode();
    }
    if (getBoolsCount() > 0) {
      hash = (37 * hash) + BOOLS_FIELD_NUMBER;
      hash = (53 * hash) + getBoolsList().hashCode();
    }
    if (getBytesCount() > 0) {
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytesList().hashCode();
    }
    if (getStringValuesCount() > 0) {
      hash = (37 * hash) + STRING_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getStringValuesList().hashCode();
    }
    if (getTimestampsCount() > 0) {
      hash = (37 * hash) + TIMESTAMPS_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampsList().hashCode();
    }
    if (getNestedRepeatedCount() > 0) {
      hash = (37 * hash) + NESTED_REPEATED_FIELD_NUMBER;
      hash = (53 * hash) + getNestedRepeatedList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amstee.flink.formats.proto.test.v1.RepeatedTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amstee.flink.formats.proto.test.v1.RepeatedTest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amstee.flink.formats.proto.test.v1.RepeatedTest)
      com.amstee.flink.formats.proto.test.v1.RepeatedTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amstee.flink.formats.proto.test.v1.RepeatedTest.class, com.amstee.flink.formats.proto.test.v1.RepeatedTest.Builder.class);
    }

    // Construct using com.amstee.flink.formats.proto.test.v1.RepeatedTest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      values_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      numbers_ = emptyIntList();
      floats_ = emptyFloatList();
      doubles_ = emptyDoubleList();
      bools_ = emptyBooleanList();
      bytes_ = emptyList(com.google.protobuf.ByteString.class);
      if (stringValuesBuilder_ == null) {
        stringValues_ = java.util.Collections.emptyList();
      } else {
        stringValues_ = null;
        stringValuesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (timestampsBuilder_ == null) {
        timestamps_ = java.util.Collections.emptyList();
      } else {
        timestamps_ = null;
        timestampsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      if (nestedRepeatedBuilder_ == null) {
        nestedRepeated_ = java.util.Collections.emptyList();
      } else {
        nestedRepeated_ = null;
        nestedRepeatedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_descriptor;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedTest getDefaultInstanceForType() {
      return com.amstee.flink.formats.proto.test.v1.RepeatedTest.getDefaultInstance();
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedTest build() {
      com.amstee.flink.formats.proto.test.v1.RepeatedTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedTest buildPartial() {
      com.amstee.flink.formats.proto.test.v1.RepeatedTest result = new com.amstee.flink.formats.proto.test.v1.RepeatedTest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.amstee.flink.formats.proto.test.v1.RepeatedTest result) {
      if (stringValuesBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          stringValues_ = java.util.Collections.unmodifiableList(stringValues_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.stringValues_ = stringValues_;
      } else {
        result.stringValues_ = stringValuesBuilder_.build();
      }
      if (timestampsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          timestamps_ = java.util.Collections.unmodifiableList(timestamps_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.timestamps_ = timestamps_;
      } else {
        result.timestamps_ = timestampsBuilder_.build();
      }
      if (nestedRepeatedBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          nestedRepeated_ = java.util.Collections.unmodifiableList(nestedRepeated_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.nestedRepeated_ = nestedRepeated_;
      } else {
        result.nestedRepeated_ = nestedRepeatedBuilder_.build();
      }
    }

    private void buildPartial0(com.amstee.flink.formats.proto.test.v1.RepeatedTest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        values_.makeImmutable();
        result.values_ = values_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        numbers_.makeImmutable();
        result.numbers_ = numbers_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        floats_.makeImmutable();
        result.floats_ = floats_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        doubles_.makeImmutable();
        result.doubles_ = doubles_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        bools_.makeImmutable();
        result.bools_ = bools_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        bytes_.makeImmutable();
        result.bytes_ = bytes_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amstee.flink.formats.proto.test.v1.RepeatedTest) {
        return mergeFrom((com.amstee.flink.formats.proto.test.v1.RepeatedTest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amstee.flink.formats.proto.test.v1.RepeatedTest other) {
      if (other == com.amstee.flink.formats.proto.test.v1.RepeatedTest.getDefaultInstance()) return this;
      if (!other.values_.isEmpty()) {
        if (values_.isEmpty()) {
          values_ = other.values_;
          bitField0_ |= 0x00000001;
        } else {
          ensureValuesIsMutable();
          values_.addAll(other.values_);
        }
        onChanged();
      }
      if (!other.numbers_.isEmpty()) {
        if (numbers_.isEmpty()) {
          numbers_ = other.numbers_;
          numbers_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureNumbersIsMutable();
          numbers_.addAll(other.numbers_);
        }
        onChanged();
      }
      if (!other.floats_.isEmpty()) {
        if (floats_.isEmpty()) {
          floats_ = other.floats_;
          floats_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureFloatsIsMutable();
          floats_.addAll(other.floats_);
        }
        onChanged();
      }
      if (!other.doubles_.isEmpty()) {
        if (doubles_.isEmpty()) {
          doubles_ = other.doubles_;
          doubles_.makeImmutable();
          bitField0_ |= 0x00000008;
        } else {
          ensureDoublesIsMutable();
          doubles_.addAll(other.doubles_);
        }
        onChanged();
      }
      if (!other.bools_.isEmpty()) {
        if (bools_.isEmpty()) {
          bools_ = other.bools_;
          bools_.makeImmutable();
          bitField0_ |= 0x00000010;
        } else {
          ensureBoolsIsMutable();
          bools_.addAll(other.bools_);
        }
        onChanged();
      }
      if (!other.bytes_.isEmpty()) {
        if (bytes_.isEmpty()) {
          bytes_ = other.bytes_;
          bytes_.makeImmutable();
          bitField0_ |= 0x00000020;
        } else {
          ensureBytesIsMutable();
          bytes_.addAll(other.bytes_);
        }
        onChanged();
      }
      if (stringValuesBuilder_ == null) {
        if (!other.stringValues_.isEmpty()) {
          if (stringValues_.isEmpty()) {
            stringValues_ = other.stringValues_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureStringValuesIsMutable();
            stringValues_.addAll(other.stringValues_);
          }
          onChanged();
        }
      } else {
        if (!other.stringValues_.isEmpty()) {
          if (stringValuesBuilder_.isEmpty()) {
            stringValuesBuilder_.dispose();
            stringValuesBuilder_ = null;
            stringValues_ = other.stringValues_;
            bitField0_ = (bitField0_ & ~0x00000040);
            stringValuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStringValuesFieldBuilder() : null;
          } else {
            stringValuesBuilder_.addAllMessages(other.stringValues_);
          }
        }
      }
      if (timestampsBuilder_ == null) {
        if (!other.timestamps_.isEmpty()) {
          if (timestamps_.isEmpty()) {
            timestamps_ = other.timestamps_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureTimestampsIsMutable();
            timestamps_.addAll(other.timestamps_);
          }
          onChanged();
        }
      } else {
        if (!other.timestamps_.isEmpty()) {
          if (timestampsBuilder_.isEmpty()) {
            timestampsBuilder_.dispose();
            timestampsBuilder_ = null;
            timestamps_ = other.timestamps_;
            bitField0_ = (bitField0_ & ~0x00000080);
            timestampsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTimestampsFieldBuilder() : null;
          } else {
            timestampsBuilder_.addAllMessages(other.timestamps_);
          }
        }
      }
      if (nestedRepeatedBuilder_ == null) {
        if (!other.nestedRepeated_.isEmpty()) {
          if (nestedRepeated_.isEmpty()) {
            nestedRepeated_ = other.nestedRepeated_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureNestedRepeatedIsMutable();
            nestedRepeated_.addAll(other.nestedRepeated_);
          }
          onChanged();
        }
      } else {
        if (!other.nestedRepeated_.isEmpty()) {
          if (nestedRepeatedBuilder_.isEmpty()) {
            nestedRepeatedBuilder_.dispose();
            nestedRepeatedBuilder_ = null;
            nestedRepeated_ = other.nestedRepeated_;
            bitField0_ = (bitField0_ & ~0x00000100);
            nestedRepeatedBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNestedRepeatedFieldBuilder() : null;
          } else {
            nestedRepeatedBuilder_.addAllMessages(other.nestedRepeated_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureValuesIsMutable();
              values_.add(s);
              break;
            } // case 10
            case 16: {
              int v = input.readInt32();
              ensureNumbersIsMutable();
              numbers_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureNumbersIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                numbers_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 29: {
              float v = input.readFloat();
              ensureFloatsIsMutable();
              floats_.addFloat(v);
              break;
            } // case 29
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureFloatsIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                floats_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 33: {
              double v = input.readDouble();
              ensureDoublesIsMutable();
              doubles_.addDouble(v);
              break;
            } // case 33
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureDoublesIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                doubles_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 34
            case 40: {
              boolean v = input.readBool();
              ensureBoolsIsMutable();
              bools_.addBoolean(v);
              break;
            } // case 40
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureBoolsIsMutable(alloc / 1);
              while (input.getBytesUntilLimit() > 0) {
                bools_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            } // case 42
            case 50: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureBytesIsMutable();
              bytes_.add(v);
              break;
            } // case 50
            case 58: {
              com.google.protobuf.StringValue m =
                  input.readMessage(
                      com.google.protobuf.StringValue.parser(),
                      extensionRegistry);
              if (stringValuesBuilder_ == null) {
                ensureStringValuesIsMutable();
                stringValues_.add(m);
              } else {
                stringValuesBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              com.google.protobuf.Timestamp m =
                  input.readMessage(
                      com.google.protobuf.Timestamp.parser(),
                      extensionRegistry);
              if (timestampsBuilder_ == null) {
                ensureTimestampsIsMutable();
                timestamps_.add(m);
              } else {
                timestampsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              com.amstee.flink.formats.proto.test.v1.NestedRepeated m =
                  input.readMessage(
                      com.amstee.flink.formats.proto.test.v1.NestedRepeated.parser(),
                      extensionRegistry);
              if (nestedRepeatedBuilder_ == null) {
                ensureNestedRepeatedIsMutable();
                nestedRepeated_.add(m);
              } else {
                nestedRepeatedBuilder_.addMessage(m);
              }
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList values_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureValuesIsMutable() {
      if (!values_.isModifiable()) {
        values_ = new com.google.protobuf.LazyStringArrayList(values_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @return A list containing the values.
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      values_.makeImmutable();
      return values_;
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @return The count of values.
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the values at the given index.
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @param index The index to set the value at.
     * @param value The values to set.
     * @return This builder for chaining.
     */
    public Builder setValues(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureValuesIsMutable();
      values_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @param value The values to add.
     * @return This builder for chaining.
     */
    public Builder addValues(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureValuesIsMutable();
      values_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @param values The values to add.
     * @return This builder for chaining.
     */
    public Builder addAllValues(
        java.lang.Iterable<java.lang.String> values) {
      ensureValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, values_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValues() {
      values_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string values = 1 [json_name = "values"];</code>
     * @param value The bytes of the values to add.
     * @return This builder for chaining.
     */
    public Builder addValuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureValuesIsMutable();
      values_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList numbers_ = emptyIntList();
    private void ensureNumbersIsMutable() {
      if (!numbers_.isModifiable()) {
        numbers_ = makeMutableCopy(numbers_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @return A list containing the numbers.
     */
    public java.util.List<java.lang.Integer>
        getNumbersList() {
      numbers_.makeImmutable();
      return numbers_;
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @return The count of numbers.
     */
    public int getNumbersCount() {
      return numbers_.size();
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @param index The index of the element to return.
     * @return The numbers at the given index.
     */
    public int getNumbers(int index) {
      return numbers_.getInt(index);
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @param index The index to set the value at.
     * @param value The numbers to set.
     * @return This builder for chaining.
     */
    public Builder setNumbers(
        int index, int value) {

      ensureNumbersIsMutable();
      numbers_.setInt(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @param value The numbers to add.
     * @return This builder for chaining.
     */
    public Builder addNumbers(int value) {

      ensureNumbersIsMutable();
      numbers_.addInt(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @param values The numbers to add.
     * @return This builder for chaining.
     */
    public Builder addAllNumbers(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, numbers_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 numbers = 2 [json_name = "numbers"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumbers() {
      numbers_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList floats_ = emptyFloatList();
    private void ensureFloatsIsMutable() {
      if (!floats_.isModifiable()) {
        floats_ = makeMutableCopy(floats_);
      }
      bitField0_ |= 0x00000004;
    }
    private void ensureFloatsIsMutable(int capacity) {
      if (!floats_.isModifiable()) {
        floats_ = makeMutableCopy(floats_, capacity);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @return A list containing the floats.
     */
    public java.util.List<java.lang.Float>
        getFloatsList() {
      floats_.makeImmutable();
      return floats_;
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @return The count of floats.
     */
    public int getFloatsCount() {
      return floats_.size();
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @param index The index of the element to return.
     * @return The floats at the given index.
     */
    public float getFloats(int index) {
      return floats_.getFloat(index);
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @param index The index to set the value at.
     * @param value The floats to set.
     * @return This builder for chaining.
     */
    public Builder setFloats(
        int index, float value) {

      ensureFloatsIsMutable();
      floats_.setFloat(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @param value The floats to add.
     * @return This builder for chaining.
     */
    public Builder addFloats(float value) {

      ensureFloatsIsMutable();
      floats_.addFloat(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @param values The floats to add.
     * @return This builder for chaining.
     */
    public Builder addAllFloats(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureFloatsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, floats_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float floats = 3 [json_name = "floats"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloats() {
      floats_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList doubles_ = emptyDoubleList();
    private void ensureDoublesIsMutable() {
      if (!doubles_.isModifiable()) {
        doubles_ = makeMutableCopy(doubles_);
      }
      bitField0_ |= 0x00000008;
    }
    private void ensureDoublesIsMutable(int capacity) {
      if (!doubles_.isModifiable()) {
        doubles_ = makeMutableCopy(doubles_, capacity);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @return A list containing the doubles.
     */
    public java.util.List<java.lang.Double>
        getDoublesList() {
      doubles_.makeImmutable();
      return doubles_;
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @return The count of doubles.
     */
    public int getDoublesCount() {
      return doubles_.size();
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @param index The index of the element to return.
     * @return The doubles at the given index.
     */
    public double getDoubles(int index) {
      return doubles_.getDouble(index);
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @param index The index to set the value at.
     * @param value The doubles to set.
     * @return This builder for chaining.
     */
    public Builder setDoubles(
        int index, double value) {

      ensureDoublesIsMutable();
      doubles_.setDouble(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @param value The doubles to add.
     * @return This builder for chaining.
     */
    public Builder addDoubles(double value) {

      ensureDoublesIsMutable();
      doubles_.addDouble(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @param values The doubles to add.
     * @return This builder for chaining.
     */
    public Builder addAllDoubles(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureDoublesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, doubles_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double doubles = 4 [json_name = "doubles"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubles() {
      doubles_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.BooleanList bools_ = emptyBooleanList();
    private void ensureBoolsIsMutable() {
      if (!bools_.isModifiable()) {
        bools_ = makeMutableCopy(bools_);
      }
      bitField0_ |= 0x00000010;
    }
    private void ensureBoolsIsMutable(int capacity) {
      if (!bools_.isModifiable()) {
        bools_ = makeMutableCopy(bools_, capacity);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @return A list containing the bools.
     */
    public java.util.List<java.lang.Boolean>
        getBoolsList() {
      bools_.makeImmutable();
      return bools_;
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @return The count of bools.
     */
    public int getBoolsCount() {
      return bools_.size();
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @param index The index of the element to return.
     * @return The bools at the given index.
     */
    public boolean getBools(int index) {
      return bools_.getBoolean(index);
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @param index The index to set the value at.
     * @param value The bools to set.
     * @return This builder for chaining.
     */
    public Builder setBools(
        int index, boolean value) {

      ensureBoolsIsMutable();
      bools_.setBoolean(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @param value The bools to add.
     * @return This builder for chaining.
     */
    public Builder addBools(boolean value) {

      ensureBoolsIsMutable();
      bools_.addBoolean(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @param values The bools to add.
     * @return This builder for chaining.
     */
    public Builder addAllBools(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureBoolsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, bools_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool bools = 5 [json_name = "bools"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBools() {
      bools_ = emptyBooleanList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> bytes_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureBytesIsMutable() {
      if (!bytes_.isModifiable()) {
        bytes_ = makeMutableCopy(bytes_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @return A list containing the bytes.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getBytesList() {
      bytes_.makeImmutable();
      return bytes_;
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @return The count of bytes.
     */
    public int getBytesCount() {
      return bytes_.size();
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @param index The index of the element to return.
     * @return The bytes at the given index.
     */
    public com.google.protobuf.ByteString getBytes(int index) {
      return bytes_.get(index);
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @param index The index to set the value at.
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureBytesIsMutable();
      bytes_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @param value The bytes to add.
     * @return This builder for chaining.
     */
    public Builder addBytes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureBytesIsMutable();
      bytes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @param values The bytes to add.
     * @return This builder for chaining.
     */
    public Builder addAllBytes(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureBytesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, bytes_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes bytes = 6 [json_name = "bytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {
      bytes_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.StringValue> stringValues_ =
      java.util.Collections.emptyList();
    private void ensureStringValuesIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        stringValues_ = new java.util.ArrayList<com.google.protobuf.StringValue>(stringValues_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringValuesBuilder_;

    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public java.util.List<com.google.protobuf.StringValue> getStringValuesList() {
      if (stringValuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stringValues_);
      } else {
        return stringValuesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public int getStringValuesCount() {
      if (stringValuesBuilder_ == null) {
        return stringValues_.size();
      } else {
        return stringValuesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public com.google.protobuf.StringValue getStringValues(int index) {
      if (stringValuesBuilder_ == null) {
        return stringValues_.get(index);
      } else {
        return stringValuesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder setStringValues(
        int index, com.google.protobuf.StringValue value) {
      if (stringValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStringValuesIsMutable();
        stringValues_.set(index, value);
        onChanged();
      } else {
        stringValuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder setStringValues(
        int index, com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValuesBuilder_ == null) {
        ensureStringValuesIsMutable();
        stringValues_.set(index, builderForValue.build());
        onChanged();
      } else {
        stringValuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder addStringValues(com.google.protobuf.StringValue value) {
      if (stringValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStringValuesIsMutable();
        stringValues_.add(value);
        onChanged();
      } else {
        stringValuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder addStringValues(
        int index, com.google.protobuf.StringValue value) {
      if (stringValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStringValuesIsMutable();
        stringValues_.add(index, value);
        onChanged();
      } else {
        stringValuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder addStringValues(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValuesBuilder_ == null) {
        ensureStringValuesIsMutable();
        stringValues_.add(builderForValue.build());
        onChanged();
      } else {
        stringValuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder addStringValues(
        int index, com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValuesBuilder_ == null) {
        ensureStringValuesIsMutable();
        stringValues_.add(index, builderForValue.build());
        onChanged();
      } else {
        stringValuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder addAllStringValues(
        java.lang.Iterable<? extends com.google.protobuf.StringValue> values) {
      if (stringValuesBuilder_ == null) {
        ensureStringValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stringValues_);
        onChanged();
      } else {
        stringValuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder clearStringValues() {
      if (stringValuesBuilder_ == null) {
        stringValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        stringValuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public Builder removeStringValues(int index) {
      if (stringValuesBuilder_ == null) {
        ensureStringValuesIsMutable();
        stringValues_.remove(index);
        onChanged();
      } else {
        stringValuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public com.google.protobuf.StringValue.Builder getStringValuesBuilder(
        int index) {
      return getStringValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringValuesOrBuilder(
        int index) {
      if (stringValuesBuilder_ == null) {
        return stringValues_.get(index);  } else {
        return stringValuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public java.util.List<? extends com.google.protobuf.StringValueOrBuilder> 
         getStringValuesOrBuilderList() {
      if (stringValuesBuilder_ != null) {
        return stringValuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stringValues_);
      }
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public com.google.protobuf.StringValue.Builder addStringValuesBuilder() {
      return getStringValuesFieldBuilder().addBuilder(
          com.google.protobuf.StringValue.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public com.google.protobuf.StringValue.Builder addStringValuesBuilder(
        int index) {
      return getStringValuesFieldBuilder().addBuilder(
          index, com.google.protobuf.StringValue.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.StringValue string_values = 7 [json_name = "stringValues"];</code>
     */
    public java.util.List<com.google.protobuf.StringValue.Builder> 
         getStringValuesBuilderList() {
      return getStringValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getStringValuesFieldBuilder() {
      if (stringValuesBuilder_ == null) {
        stringValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                stringValues_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        stringValues_ = null;
      }
      return stringValuesBuilder_;
    }

    private java.util.List<com.google.protobuf.Timestamp> timestamps_ =
      java.util.Collections.emptyList();
    private void ensureTimestampsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        timestamps_ = new java.util.ArrayList<com.google.protobuf.Timestamp>(timestamps_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampsBuilder_;

    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public java.util.List<com.google.protobuf.Timestamp> getTimestampsList() {
      if (timestampsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(timestamps_);
      } else {
        return timestampsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public int getTimestampsCount() {
      if (timestampsBuilder_ == null) {
        return timestamps_.size();
      } else {
        return timestampsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public com.google.protobuf.Timestamp getTimestamps(int index) {
      if (timestampsBuilder_ == null) {
        return timestamps_.get(index);
      } else {
        return timestampsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder setTimestamps(
        int index, com.google.protobuf.Timestamp value) {
      if (timestampsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimestampsIsMutable();
        timestamps_.set(index, value);
        onChanged();
      } else {
        timestampsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder setTimestamps(
        int index, com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampsBuilder_ == null) {
        ensureTimestampsIsMutable();
        timestamps_.set(index, builderForValue.build());
        onChanged();
      } else {
        timestampsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder addTimestamps(com.google.protobuf.Timestamp value) {
      if (timestampsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimestampsIsMutable();
        timestamps_.add(value);
        onChanged();
      } else {
        timestampsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder addTimestamps(
        int index, com.google.protobuf.Timestamp value) {
      if (timestampsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimestampsIsMutable();
        timestamps_.add(index, value);
        onChanged();
      } else {
        timestampsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder addTimestamps(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampsBuilder_ == null) {
        ensureTimestampsIsMutable();
        timestamps_.add(builderForValue.build());
        onChanged();
      } else {
        timestampsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder addTimestamps(
        int index, com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampsBuilder_ == null) {
        ensureTimestampsIsMutable();
        timestamps_.add(index, builderForValue.build());
        onChanged();
      } else {
        timestampsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder addAllTimestamps(
        java.lang.Iterable<? extends com.google.protobuf.Timestamp> values) {
      if (timestampsBuilder_ == null) {
        ensureTimestampsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timestamps_);
        onChanged();
      } else {
        timestampsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder clearTimestamps() {
      if (timestampsBuilder_ == null) {
        timestamps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        timestampsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public Builder removeTimestamps(int index) {
      if (timestampsBuilder_ == null) {
        ensureTimestampsIsMutable();
        timestamps_.remove(index);
        onChanged();
      } else {
        timestampsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampsBuilder(
        int index) {
      return getTimestampsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampsOrBuilder(
        int index) {
      if (timestampsBuilder_ == null) {
        return timestamps_.get(index);  } else {
        return timestampsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
         getTimestampsOrBuilderList() {
      if (timestampsBuilder_ != null) {
        return timestampsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(timestamps_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public com.google.protobuf.Timestamp.Builder addTimestampsBuilder() {
      return getTimestampsFieldBuilder().addBuilder(
          com.google.protobuf.Timestamp.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public com.google.protobuf.Timestamp.Builder addTimestampsBuilder(
        int index) {
      return getTimestampsFieldBuilder().addBuilder(
          index, com.google.protobuf.Timestamp.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Timestamp timestamps = 8 [json_name = "timestamps"];</code>
     */
    public java.util.List<com.google.protobuf.Timestamp.Builder> 
         getTimestampsBuilderList() {
      return getTimestampsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampsFieldBuilder() {
      if (timestampsBuilder_ == null) {
        timestampsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                timestamps_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        timestamps_ = null;
      }
      return timestampsBuilder_;
    }

    private java.util.List<com.amstee.flink.formats.proto.test.v1.NestedRepeated> nestedRepeated_ =
      java.util.Collections.emptyList();
    private void ensureNestedRepeatedIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        nestedRepeated_ = new java.util.ArrayList<com.amstee.flink.formats.proto.test.v1.NestedRepeated>(nestedRepeated_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.amstee.flink.formats.proto.test.v1.NestedRepeated, com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder, com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder> nestedRepeatedBuilder_;

    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public java.util.List<com.amstee.flink.formats.proto.test.v1.NestedRepeated> getNestedRepeatedList() {
      if (nestedRepeatedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nestedRepeated_);
      } else {
        return nestedRepeatedBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public int getNestedRepeatedCount() {
      if (nestedRepeatedBuilder_ == null) {
        return nestedRepeated_.size();
      } else {
        return nestedRepeatedBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.NestedRepeated getNestedRepeated(int index) {
      if (nestedRepeatedBuilder_ == null) {
        return nestedRepeated_.get(index);
      } else {
        return nestedRepeatedBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder setNestedRepeated(
        int index, com.amstee.flink.formats.proto.test.v1.NestedRepeated value) {
      if (nestedRepeatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.set(index, value);
        onChanged();
      } else {
        nestedRepeatedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder setNestedRepeated(
        int index, com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder builderForValue) {
      if (nestedRepeatedBuilder_ == null) {
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.set(index, builderForValue.build());
        onChanged();
      } else {
        nestedRepeatedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder addNestedRepeated(com.amstee.flink.formats.proto.test.v1.NestedRepeated value) {
      if (nestedRepeatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.add(value);
        onChanged();
      } else {
        nestedRepeatedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder addNestedRepeated(
        int index, com.amstee.flink.formats.proto.test.v1.NestedRepeated value) {
      if (nestedRepeatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.add(index, value);
        onChanged();
      } else {
        nestedRepeatedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder addNestedRepeated(
        com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder builderForValue) {
      if (nestedRepeatedBuilder_ == null) {
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.add(builderForValue.build());
        onChanged();
      } else {
        nestedRepeatedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder addNestedRepeated(
        int index, com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder builderForValue) {
      if (nestedRepeatedBuilder_ == null) {
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.add(index, builderForValue.build());
        onChanged();
      } else {
        nestedRepeatedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder addAllNestedRepeated(
        java.lang.Iterable<? extends com.amstee.flink.formats.proto.test.v1.NestedRepeated> values) {
      if (nestedRepeatedBuilder_ == null) {
        ensureNestedRepeatedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nestedRepeated_);
        onChanged();
      } else {
        nestedRepeatedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder clearNestedRepeated() {
      if (nestedRepeatedBuilder_ == null) {
        nestedRepeated_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        nestedRepeatedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public Builder removeNestedRepeated(int index) {
      if (nestedRepeatedBuilder_ == null) {
        ensureNestedRepeatedIsMutable();
        nestedRepeated_.remove(index);
        onChanged();
      } else {
        nestedRepeatedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder getNestedRepeatedBuilder(
        int index) {
      return getNestedRepeatedFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder getNestedRepeatedOrBuilder(
        int index) {
      if (nestedRepeatedBuilder_ == null) {
        return nestedRepeated_.get(index);  } else {
        return nestedRepeatedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public java.util.List<? extends com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder> 
         getNestedRepeatedOrBuilderList() {
      if (nestedRepeatedBuilder_ != null) {
        return nestedRepeatedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nestedRepeated_);
      }
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder addNestedRepeatedBuilder() {
      return getNestedRepeatedFieldBuilder().addBuilder(
          com.amstee.flink.formats.proto.test.v1.NestedRepeated.getDefaultInstance());
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder addNestedRepeatedBuilder(
        int index) {
      return getNestedRepeatedFieldBuilder().addBuilder(
          index, com.amstee.flink.formats.proto.test.v1.NestedRepeated.getDefaultInstance());
    }
    /**
     * <code>repeated .amstee.flink.formats.proto.test.v1.NestedRepeated nested_repeated = 9 [json_name = "nestedRepeated"];</code>
     */
    public java.util.List<com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder> 
         getNestedRepeatedBuilderList() {
      return getNestedRepeatedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.amstee.flink.formats.proto.test.v1.NestedRepeated, com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder, com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder> 
        getNestedRepeatedFieldBuilder() {
      if (nestedRepeatedBuilder_ == null) {
        nestedRepeatedBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.amstee.flink.formats.proto.test.v1.NestedRepeated, com.amstee.flink.formats.proto.test.v1.NestedRepeated.Builder, com.amstee.flink.formats.proto.test.v1.NestedRepeatedOrBuilder>(
                nestedRepeated_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        nestedRepeated_ = null;
      }
      return nestedRepeatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amstee.flink.formats.proto.test.v1.RepeatedTest)
  }

  // @@protoc_insertion_point(class_scope:amstee.flink.formats.proto.test.v1.RepeatedTest)
  private static final com.amstee.flink.formats.proto.test.v1.RepeatedTest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amstee.flink.formats.proto.test.v1.RepeatedTest();
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepeatedTest>
      PARSER = new com.google.protobuf.AbstractParser<RepeatedTest>() {
    @java.lang.Override
    public RepeatedTest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RepeatedTest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepeatedTest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.RepeatedTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

