// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_repeated_nested.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

/**
 * Protobuf type {@code amstee.flink.formats.proto.test.v1.RepeatedMessageTest}
 */
public final class RepeatedMessageTest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amstee.flink.formats.proto.test.v1.RepeatedMessageTest)
    RepeatedMessageTestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RepeatedMessageTest.newBuilder() to construct.
  private RepeatedMessageTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepeatedMessageTest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RepeatedMessageTest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.class, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.Builder.class);
  }

  public interface InnerMessageTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 a = 1 [json_name = "a"];</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>optional int32 a = 1 [json_name = "a"];</code>
     * @return The a.
     */
    int getA();

    /**
     * <code>optional int64 b = 2 [json_name = "b"];</code>
     * @return Whether the b field is set.
     */
    boolean hasB();
    /**
     * <code>optional int64 b = 2 [json_name = "b"];</code>
     * @return The b.
     */
    long getB();
  }
  /**
   * Protobuf type {@code amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest}
   */
  public static final class InnerMessageTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
      InnerMessageTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerMessageTest.newBuilder() to construct.
    private InnerMessageTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerMessageTest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InnerMessageTest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.class, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder.class);
    }

    private int bitField0_;
    public static final int A_FIELD_NUMBER = 1;
    private int a_ = 0;
    /**
     * <code>optional int32 a = 1 [json_name = "a"];</code>
     * @return Whether the a field is set.
     */
    @java.lang.Override
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 a = 1 [json_name = "a"];</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private long b_ = 0L;
    /**
     * <code>optional int64 b = 2 [json_name = "b"];</code>
     * @return Whether the b field is set.
     */
    @java.lang.Override
    public boolean hasB() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 b = 2 [json_name = "b"];</code>
     * @return The b.
     */
    @java.lang.Override
    public long getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, a_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, b_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, b_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)) {
        return super.equals(obj);
      }
      com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest other = (com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest) obj;

      if (hasA() != other.hasA()) return false;
      if (hasA()) {
        if (getA()
            != other.getA()) return false;
      }
      if (hasB() != other.hasB()) return false;
      if (hasB()) {
        if (getB()
            != other.getB()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA();
      }
      if (hasB()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getB());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
        com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.class, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder.class);
      }

      // Construct using com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = 0;
        b_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
      }

      @java.lang.Override
      public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest getDefaultInstanceForType() {
        return com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance();
      }

      @java.lang.Override
      public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest build() {
        com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest buildPartial() {
        com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest result = new com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = a_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.b_ = b_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest) {
          return mergeFrom((com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest other) {
        if (other == com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance()) return this;
        if (other.hasA()) {
          setA(other.getA());
        }
        if (other.hasB()) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                a_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                b_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int a_ ;
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return Whether the a field is set.
       */
      @java.lang.Override
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return The a.
       */
      @java.lang.Override
      public int getA() {
        return a_;
      }
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(int value) {

        a_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        onChanged();
        return this;
      }

      private long b_ ;
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return Whether the b field is set.
       */
      @java.lang.Override
      public boolean hasB() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return The b.
       */
      @java.lang.Override
      public long getB() {
        return b_;
      }
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(long value) {

        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
    }

    // @@protoc_insertion_point(class_scope:amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
    private static final com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest();
    }

    public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InnerMessageTest>
        PARSER = new com.google.protobuf.AbstractParser<InnerMessageTest>() {
      @java.lang.Override
      public InnerMessageTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InnerMessageTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InnerMessageTest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int D_FIELD_NUMBER = 4;
  private com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d_;
  /**
   * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
   * @return Whether the d field is set.
   */
  @java.lang.Override
  public boolean hasD() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
   * @return The d.
   */
  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest getD() {
    return d_ == null ? com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
  }
  /**
   * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
   */
  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTestOrBuilder getDOrBuilder() {
    return d_ == null ? com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getD());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getD());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest)) {
      return super.equals(obj);
    }
    com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest other = (com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest) obj;

    if (hasD() != other.hasD()) return false;
    if (hasD()) {
      if (!getD()
          .equals(other.getD())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasD()) {
      hash = (37 * hash) + D_FIELD_NUMBER;
      hash = (53 * hash) + getD().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amstee.flink.formats.proto.test.v1.RepeatedMessageTest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amstee.flink.formats.proto.test.v1.RepeatedMessageTest)
      com.amstee.flink.formats.proto.test.v1.RepeatedMessageTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.class, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.Builder.class);
    }

    // Construct using com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      d_ = null;
      if (dBuilder_ != null) {
        dBuilder_.dispose();
        dBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amstee.flink.formats.proto.test.v1.TestRepeatedNestedProto.internal_static_amstee_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest getDefaultInstanceForType() {
      return com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.getDefaultInstance();
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest build() {
      com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest buildPartial() {
      com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest result = new com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.d_ = dBuilder_ == null
            ? d_
            : dBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest) {
        return mergeFrom((com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest other) {
      if (other == com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.getDefaultInstance()) return this;
      if (other.hasD()) {
        mergeD(other.getD());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              input.readMessage(
                  getDFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTestOrBuilder> dBuilder_;
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     * @return Whether the d field is set.
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     * @return The d.
     */
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest getD() {
      if (dBuilder_ == null) {
        return d_ == null ? com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
      } else {
        return dBuilder_.getMessage();
      }
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    public Builder setD(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest value) {
      if (dBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d_ = value;
      } else {
        dBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    public Builder setD(
        com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder builderForValue) {
      if (dBuilder_ == null) {
        d_ = builderForValue.build();
      } else {
        dBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    public Builder mergeD(com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest value) {
      if (dBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          d_ != null &&
          d_ != com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance()) {
          getDBuilder().mergeFrom(value);
        } else {
          d_ = value;
        }
      } else {
        dBuilder_.mergeFrom(value);
      }
      if (d_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    public Builder clearD() {
      bitField0_ = (bitField0_ & ~0x00000001);
      d_ = null;
      if (dBuilder_ != null) {
        dBuilder_.dispose();
        dBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder getDBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDFieldBuilder().getBuilder();
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTestOrBuilder getDOrBuilder() {
      if (dBuilder_ != null) {
        return dBuilder_.getMessageOrBuilder();
      } else {
        return d_ == null ?
            com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
      }
    }
    /**
     * <code>.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTestOrBuilder> 
        getDFieldBuilder() {
      if (dBuilder_ == null) {
        dBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest.Builder, com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTestOrBuilder>(
                getD(),
                getParentForChildren(),
                isClean());
        d_ = null;
      }
      return dBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amstee.flink.formats.proto.test.v1.RepeatedMessageTest)
  }

  // @@protoc_insertion_point(class_scope:amstee.flink.formats.proto.test.v1.RepeatedMessageTest)
  private static final com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest();
  }

  public static com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepeatedMessageTest>
      PARSER = new com.google.protobuf.AbstractParser<RepeatedMessageTest>() {
    @java.lang.Override
    public RepeatedMessageTest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RepeatedMessageTest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepeatedMessageTest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.RepeatedMessageTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

