// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_repeated.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public final class TestRepeatedProto {
  private TestRepeatedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_NestedRepeated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_NestedRepeated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/flink/formats/proto/test/v1/test_repea" +
      "ted.proto\022\"amstee.flink.formats.proto.te" +
      "st.v1\032\037google/protobuf/timestamp.proto\032\036" +
      "google/protobuf/wrappers.proto\"&\n\016Nested" +
      "Repeated\022\024\n\005value\030\001 \001(\tR\005value\"\372\002\n\014Repea" +
      "tedTest\022\026\n\006values\030\001 \003(\tR\006values\022\030\n\007numbe" +
      "rs\030\002 \003(\005R\007numbers\022\026\n\006floats\030\003 \003(\002R\006float" +
      "s\022\030\n\007doubles\030\004 \003(\001R\007doubles\022\024\n\005bools\030\005 \003" +
      "(\010R\005bools\022\024\n\005bytes\030\006 \003(\014R\005bytes\022A\n\rstrin" +
      "g_values\030\007 \003(\0132\034.google.protobuf.StringV" +
      "alueR\014stringValues\022:\n\ntimestamps\030\010 \003(\0132\032" +
      ".google.protobuf.TimestampR\ntimestamps\022[" +
      "\n\017nested_repeated\030\t \003(\01322.amstee.flink.f" +
      "ormats.proto.test.v1.NestedRepeatedR\016nes" +
      "tedRepeatedB\352\001\n&com.amstee.flink.formats" +
      ".proto.test.v1B\021TestRepeatedProtoP\001\242\002\005AF" +
      "FPT\252\002\"Amstee.Flink.Formats.Proto.Test.V1" +
      "\312\002\"Amstee\\Flink\\Formats\\Proto\\Test\\V1\342\002." +
      "Amstee\\Flink\\Formats\\Proto\\Test\\V1\\GPBMe" +
      "tadata\352\002\'Amstee::Flink::Formats::Proto::" +
      "Test::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_amstee_flink_formats_proto_test_v1_NestedRepeated_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amstee_flink_formats_proto_test_v1_NestedRepeated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_NestedRepeated_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_RepeatedTest_descriptor,
        new java.lang.String[] { "Values", "Numbers", "Floats", "Doubles", "Bools", "Bytes", "StringValues", "Timestamps", "NestedRepeated", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
