// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_map.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public final class TestMapProto {
  private TestMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_NestedMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_NestedMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_MapTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_MapTest_NestedMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*flink/formats/proto/test/v1/test_map.p" +
      "roto\022\"amstee.flink.formats.proto.test.v1" +
      "\"\033\n\tNestedMap\022\016\n\002id\030\001 \001(\tR\002id\"\203\003\n\007MapTes" +
      "t\022l\n\021simple_string_map\030\001 \003(\0132@.amstee.fl" +
      "ink.formats.proto.test.v1.MapTest.Simple" +
      "StringMapEntryR\017simpleStringMap\022Y\n\nneste" +
      "d_map\030\002 \003(\0132:.amstee.flink.formats.proto" +
      ".test.v1.MapTest.NestedMapEntryR\tnestedM" +
      "ap\032B\n\024SimpleStringMapEntry\022\020\n\003key\030\001 \001(\tR" +
      "\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032k\n\016Nested" +
      "MapEntry\022\020\n\003key\030\001 \001(\tR\003key\022C\n\005value\030\002 \001(" +
      "\0132-.amstee.flink.formats.proto.test.v1.N" +
      "estedMapR\005value:\0028\001B\345\001\n&com.amstee.flink" +
      ".formats.proto.test.v1B\014TestMapProtoP\001\242\002" +
      "\005AFFPT\252\002\"Amstee.Flink.Formats.Proto.Test" +
      ".V1\312\002\"Amstee\\Flink\\Formats\\Proto\\Test\\V1" +
      "\342\002.Amstee\\Flink\\Formats\\Proto\\Test\\V1\\GP" +
      "BMetadata\352\002\'Amstee::Flink::Formats::Prot" +
      "o::Test::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_amstee_flink_formats_proto_test_v1_NestedMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amstee_flink_formats_proto_test_v1_NestedMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_NestedMap_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_MapTest_descriptor,
        new java.lang.String[] { "SimpleStringMap", "NestedMap", });
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor =
      internal_static_amstee_flink_formats_proto_test_v1_MapTest_descriptor.getNestedTypes().get(0);
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor =
      internal_static_amstee_flink_formats_proto_test_v1_MapTest_descriptor.getNestedTypes().get(1);
    internal_static_amstee_flink_formats_proto_test_v1_MapTest_NestedMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
