// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_enums.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public interface TestEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amstee.flink.formats.proto.test.v1.TestEnum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.amstee.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.amstee.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  com.amstee.flink.formats.proto.test.v1.MessageType getType();

  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
   * @return A list containing the status.
   */
  java.util.List<com.amstee.flink.formats.proto.test.v1.MessageStatus> getStatusList();
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
   * @return The count of status.
   */
  int getStatusCount();
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
   * @param index The index of the element to return.
   * @return The status at the given index.
   */
  com.amstee.flink.formats.proto.test.v1.MessageStatus getStatus(int index);
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
   * @return A list containing the enum numeric values on the wire for status.
   */
  java.util.List<java.lang.Integer>
  getStatusValueList();
  /**
   * <code>repeated .amstee.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of status at the given index.
   */
  int getStatusValue(int index);

  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  int getStatusMapCount();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  boolean containsStatusMap(
      java.lang.String key);
  /**
   * Use {@link #getStatusMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.amstee.flink.formats.proto.test.v1.MessageStatus>
  getStatusMap();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  java.util.Map<java.lang.String, com.amstee.flink.formats.proto.test.v1.MessageStatus>
  getStatusMapMap();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  /* nullable */
com.amstee.flink.formats.proto.test.v1.MessageStatus getStatusMapOrDefault(
      java.lang.String key,
      /* nullable */
com.amstee.flink.formats.proto.test.v1.MessageStatus         defaultValue);
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  com.amstee.flink.formats.proto.test.v1.MessageStatus getStatusMapOrThrow(
      java.lang.String key);
  /**
   * Use {@link #getStatusMapValueMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getStatusMapValue();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getStatusMapValueMap();
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  int getStatusMapValueOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, .amstee.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
   */
  int getStatusMapValueOrThrow(
      java.lang.String key);
}
