// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_big.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public final class TestBigProto {
  private TestBigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*flink/formats/proto/test/v1/test_big.p" +
      "roto\022\"amstee.flink.formats.proto.test.v1" +
      "\"\300\010\n\014BigPbMessage\022\036\n\013int_field_1\030\001 \001(\005R\t" +
      "intField1\022 \n\014bool_field_2\030\002 \001(\010R\nboolFie" +
      "ld2\022$\n\016string_field_3\030\003 \001(\tR\014stringField" +
      "3\022\"\n\rbytes_field_4\030\004 \001(\014R\013bytesField4\022$\n" +
      "\016double_field_5\030\005 \001(\001R\014doubleField5\022\"\n\rf" +
      "loat_field_6\030\006 \001(\002R\013floatField6\022$\n\016uint3" +
      "2_field_7\030\007 \001(\rR\014uint32Field7\022\"\n\rint64_f" +
      "ield_8\030\010 \001(\003R\013int64Field8\022$\n\016uint64_fiel" +
      "d_9\030\t \001(\004R\014uint64Field9\022$\n\016bytes_field_1" +
      "0\030\n \001(\014R\014bytesField10\022&\n\017double_field_11" +
      "\030\013 \001(\001R\rdoubleField11\022$\n\016bytes_field_12\030" +
      "\014 \001(\014R\014bytesField12\022\"\n\rbool_field_13\030\r \001" +
      "(\010R\013boolField13\022&\n\017string_field_14\030\016 \001(\t" +
      "R\rstringField14\022$\n\016float_field_15\030\017 \001(\002R" +
      "\014floatField15\022$\n\016int32_field_16\030\020 \001(\005R\014i" +
      "nt32Field16\022$\n\016bytes_field_17\030\021 \001(\014R\014byt" +
      "esField17\022\"\n\rbool_field_18\030\022 \001(\010R\013boolFi" +
      "eld18\022&\n\017string_field_19\030\023 \001(\tR\rstringFi" +
      "eld19\022$\n\016float_field_20\030\024 \001(\002R\014floatFiel" +
      "d20\022(\n\020fixed32_field_21\030\025 \001(\007R\016fixed32Fi" +
      "eld21\022(\n\020fixed64_field_22\030\026 \001(\006R\016fixed64" +
      "Field22\022*\n\021sfixed32_field_23\030\027 \001(\017R\017sfix" +
      "ed32Field23\022*\n\021sfixed64_field_24\030\030 \001(\020R\017" +
      "sfixed64Field24\022&\n\017double_field_25\030\031 \001(\001" +
      "R\rdoubleField25\022&\n\017uint32_field_26\030\032 \001(\r" +
      "R\ruint32Field26\022&\n\017uint64_field_27\030\033 \001(\004" +
      "R\ruint64Field27\022\"\n\rbool_field_28\030\034 \001(\010R\013" +
      "boolField28B\345\001\n&com.amstee.flink.formats" +
      ".proto.test.v1B\014TestBigProtoP\001\242\002\005AFFPT\252\002" +
      "\"Amstee.Flink.Formats.Proto.Test.V1\312\002\"Am" +
      "stee\\Flink\\Formats\\Proto\\Test\\V1\342\002.Amste" +
      "e\\Flink\\Formats\\Proto\\Test\\V1\\GPBMetadat" +
      "a\352\002\'Amstee::Flink::Formats::Proto::Test:" +
      ":V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amstee_flink_formats_proto_test_v1_BigPbMessage_descriptor,
        new java.lang.String[] { "IntField1", "BoolField2", "StringField3", "BytesField4", "DoubleField5", "FloatField6", "Uint32Field7", "Int64Field8", "Uint64Field9", "BytesField10", "DoubleField11", "BytesField12", "BoolField13", "StringField14", "FloatField15", "Int32Field16", "BytesField17", "BoolField18", "StringField19", "FloatField20", "Fixed32Field21", "Fixed64Field22", "Sfixed32Field23", "Sfixed64Field24", "DoubleField25", "Uint32Field26", "Uint64Field27", "BoolField28", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
