// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_wrapper_types.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

/**
 * Protobuf type {@code amstee.flink.formats.proto.test.v1.WrapperTypesTest}
 */
public final class WrapperTypesTest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amstee.flink.formats.proto.test.v1.WrapperTypesTest)
    WrapperTypesTestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WrapperTypesTest.newBuilder() to construct.
  private WrapperTypesTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WrapperTypesTest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WrapperTypesTest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amstee.flink.formats.proto.test.v1.TestWrapperTypesProto.internal_static_amstee_flink_formats_proto_test_v1_WrapperTypesTest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amstee.flink.formats.proto.test.v1.TestWrapperTypesProto.internal_static_amstee_flink_formats_proto_test_v1_WrapperTypesTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.class, com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.Builder.class);
  }

  private int bitField0_;
  public static final int INT32VALUE_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value int32Value_;
  /**
   * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
   * @return Whether the int32Value field is set.
   */
  @java.lang.Override
  public boolean hasInt32Value() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
   * @return The int32Value.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getInt32Value() {
    return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
  }
  /**
   * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder() {
    return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
  }

  public static final int INT64VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.Int64Value int64Value_;
  /**
   * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
   * @return Whether the int64Value field is set.
   */
  @java.lang.Override
  public boolean hasInt64Value() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
   * @return The int64Value.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getInt64Value() {
    return int64Value_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : int64Value_;
  }
  /**
   * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getInt64ValueOrBuilder() {
    return int64Value_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : int64Value_;
  }

  public static final int UINT32VALUE_FIELD_NUMBER = 3;
  private com.google.protobuf.UInt32Value uint32Value_;
  /**
   * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
   * @return Whether the uint32Value field is set.
   */
  @java.lang.Override
  public boolean hasUint32Value() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
   * @return The uint32Value.
   */
  @java.lang.Override
  public com.google.protobuf.UInt32Value getUint32Value() {
    return uint32Value_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : uint32Value_;
  }
  /**
   * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.UInt32ValueOrBuilder getUint32ValueOrBuilder() {
    return uint32Value_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : uint32Value_;
  }

  public static final int UINT64VALUE_FIELD_NUMBER = 4;
  private com.google.protobuf.UInt64Value uint64Value_;
  /**
   * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
   * @return Whether the uint64Value field is set.
   */
  @java.lang.Override
  public boolean hasUint64Value() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
   * @return The uint64Value.
   */
  @java.lang.Override
  public com.google.protobuf.UInt64Value getUint64Value() {
    return uint64Value_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : uint64Value_;
  }
  /**
   * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.UInt64ValueOrBuilder getUint64ValueOrBuilder() {
    return uint64Value_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : uint64Value_;
  }

  public static final int FLOATVALUE_FIELD_NUMBER = 5;
  private com.google.protobuf.FloatValue floatValue_;
  /**
   * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
   * @return Whether the floatValue field is set.
   */
  @java.lang.Override
  public boolean hasFloatValue() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
   * @return The floatValue.
   */
  @java.lang.Override
  public com.google.protobuf.FloatValue getFloatValue() {
    return floatValue_ == null ? com.google.protobuf.FloatValue.getDefaultInstance() : floatValue_;
  }
  /**
   * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.FloatValueOrBuilder getFloatValueOrBuilder() {
    return floatValue_ == null ? com.google.protobuf.FloatValue.getDefaultInstance() : floatValue_;
  }

  public static final int DOUBLEVALUE_FIELD_NUMBER = 6;
  private com.google.protobuf.DoubleValue doubleValue_;
  /**
   * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
   * @return Whether the doubleValue field is set.
   */
  @java.lang.Override
  public boolean hasDoubleValue() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
   * @return The doubleValue.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getDoubleValue() {
    return doubleValue_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : doubleValue_;
  }
  /**
   * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getDoubleValueOrBuilder() {
    return doubleValue_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : doubleValue_;
  }

  public static final int BOOLVALUE_FIELD_NUMBER = 7;
  private com.google.protobuf.BoolValue boolValue_;
  /**
   * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
   * @return Whether the boolValue field is set.
   */
  @java.lang.Override
  public boolean hasBoolValue() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
   * @return The boolValue.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getBoolValue() {
    return boolValue_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : boolValue_;
  }
  /**
   * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getBoolValueOrBuilder() {
    return boolValue_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : boolValue_;
  }

  public static final int STRINGVALUE_FIELD_NUMBER = 8;
  private com.google.protobuf.StringValue stringValue_;
  /**
   * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
   * @return Whether the stringValue field is set.
   */
  @java.lang.Override
  public boolean hasStringValue() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getStringValue() {
    return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
  }
  /**
   * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder() {
    return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
  }

  public static final int BYTESVALUE_FIELD_NUMBER = 9;
  private com.google.protobuf.BytesValue bytesValue_;
  /**
   * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
   * @return Whether the bytesValue field is set.
   */
  @java.lang.Override
  public boolean hasBytesValue() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
   * @return The bytesValue.
   */
  @java.lang.Override
  public com.google.protobuf.BytesValue getBytesValue() {
    return bytesValue_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : bytesValue_;
  }
  /**
   * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BytesValueOrBuilder getBytesValueOrBuilder() {
    return bytesValue_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : bytesValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getInt32Value());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getInt64Value());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getUint32Value());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getUint64Value());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getFloatValue());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getDoubleValue());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(7, getBoolValue());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(8, getStringValue());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeMessage(9, getBytesValue());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInt32Value());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInt64Value());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUint32Value());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUint64Value());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getFloatValue());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDoubleValue());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getBoolValue());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getStringValue());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getBytesValue());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amstee.flink.formats.proto.test.v1.WrapperTypesTest)) {
      return super.equals(obj);
    }
    com.amstee.flink.formats.proto.test.v1.WrapperTypesTest other = (com.amstee.flink.formats.proto.test.v1.WrapperTypesTest) obj;

    if (hasInt32Value() != other.hasInt32Value()) return false;
    if (hasInt32Value()) {
      if (!getInt32Value()
          .equals(other.getInt32Value())) return false;
    }
    if (hasInt64Value() != other.hasInt64Value()) return false;
    if (hasInt64Value()) {
      if (!getInt64Value()
          .equals(other.getInt64Value())) return false;
    }
    if (hasUint32Value() != other.hasUint32Value()) return false;
    if (hasUint32Value()) {
      if (!getUint32Value()
          .equals(other.getUint32Value())) return false;
    }
    if (hasUint64Value() != other.hasUint64Value()) return false;
    if (hasUint64Value()) {
      if (!getUint64Value()
          .equals(other.getUint64Value())) return false;
    }
    if (hasFloatValue() != other.hasFloatValue()) return false;
    if (hasFloatValue()) {
      if (!getFloatValue()
          .equals(other.getFloatValue())) return false;
    }
    if (hasDoubleValue() != other.hasDoubleValue()) return false;
    if (hasDoubleValue()) {
      if (!getDoubleValue()
          .equals(other.getDoubleValue())) return false;
    }
    if (hasBoolValue() != other.hasBoolValue()) return false;
    if (hasBoolValue()) {
      if (!getBoolValue()
          .equals(other.getBoolValue())) return false;
    }
    if (hasStringValue() != other.hasStringValue()) return false;
    if (hasStringValue()) {
      if (!getStringValue()
          .equals(other.getStringValue())) return false;
    }
    if (hasBytesValue() != other.hasBytesValue()) return false;
    if (hasBytesValue()) {
      if (!getBytesValue()
          .equals(other.getBytesValue())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInt32Value()) {
      hash = (37 * hash) + INT32VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Value().hashCode();
    }
    if (hasInt64Value()) {
      hash = (37 * hash) + INT64VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getInt64Value().hashCode();
    }
    if (hasUint32Value()) {
      hash = (37 * hash) + UINT32VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getUint32Value().hashCode();
    }
    if (hasUint64Value()) {
      hash = (37 * hash) + UINT64VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getUint64Value().hashCode();
    }
    if (hasFloatValue()) {
      hash = (37 * hash) + FLOATVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getFloatValue().hashCode();
    }
    if (hasDoubleValue()) {
      hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDoubleValue().hashCode();
    }
    if (hasBoolValue()) {
      hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getBoolValue().hashCode();
    }
    if (hasStringValue()) {
      hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
    }
    if (hasBytesValue()) {
      hash = (37 * hash) + BYTESVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getBytesValue().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amstee.flink.formats.proto.test.v1.WrapperTypesTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amstee.flink.formats.proto.test.v1.WrapperTypesTest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amstee.flink.formats.proto.test.v1.WrapperTypesTest)
      com.amstee.flink.formats.proto.test.v1.WrapperTypesTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amstee.flink.formats.proto.test.v1.TestWrapperTypesProto.internal_static_amstee_flink_formats_proto_test_v1_WrapperTypesTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amstee.flink.formats.proto.test.v1.TestWrapperTypesProto.internal_static_amstee_flink_formats_proto_test_v1_WrapperTypesTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.class, com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.Builder.class);
    }

    // Construct using com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInt32ValueFieldBuilder();
        getInt64ValueFieldBuilder();
        getUint32ValueFieldBuilder();
        getUint64ValueFieldBuilder();
        getFloatValueFieldBuilder();
        getDoubleValueFieldBuilder();
        getBoolValueFieldBuilder();
        getStringValueFieldBuilder();
        getBytesValueFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      int32Value_ = null;
      if (int32ValueBuilder_ != null) {
        int32ValueBuilder_.dispose();
        int32ValueBuilder_ = null;
      }
      int64Value_ = null;
      if (int64ValueBuilder_ != null) {
        int64ValueBuilder_.dispose();
        int64ValueBuilder_ = null;
      }
      uint32Value_ = null;
      if (uint32ValueBuilder_ != null) {
        uint32ValueBuilder_.dispose();
        uint32ValueBuilder_ = null;
      }
      uint64Value_ = null;
      if (uint64ValueBuilder_ != null) {
        uint64ValueBuilder_.dispose();
        uint64ValueBuilder_ = null;
      }
      floatValue_ = null;
      if (floatValueBuilder_ != null) {
        floatValueBuilder_.dispose();
        floatValueBuilder_ = null;
      }
      doubleValue_ = null;
      if (doubleValueBuilder_ != null) {
        doubleValueBuilder_.dispose();
        doubleValueBuilder_ = null;
      }
      boolValue_ = null;
      if (boolValueBuilder_ != null) {
        boolValueBuilder_.dispose();
        boolValueBuilder_ = null;
      }
      stringValue_ = null;
      if (stringValueBuilder_ != null) {
        stringValueBuilder_.dispose();
        stringValueBuilder_ = null;
      }
      bytesValue_ = null;
      if (bytesValueBuilder_ != null) {
        bytesValueBuilder_.dispose();
        bytesValueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amstee.flink.formats.proto.test.v1.TestWrapperTypesProto.internal_static_amstee_flink_formats_proto_test_v1_WrapperTypesTest_descriptor;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.WrapperTypesTest getDefaultInstanceForType() {
      return com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.getDefaultInstance();
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.WrapperTypesTest build() {
      com.amstee.flink.formats.proto.test.v1.WrapperTypesTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.amstee.flink.formats.proto.test.v1.WrapperTypesTest buildPartial() {
      com.amstee.flink.formats.proto.test.v1.WrapperTypesTest result = new com.amstee.flink.formats.proto.test.v1.WrapperTypesTest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.amstee.flink.formats.proto.test.v1.WrapperTypesTest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.int32Value_ = int32ValueBuilder_ == null
            ? int32Value_
            : int32ValueBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.int64Value_ = int64ValueBuilder_ == null
            ? int64Value_
            : int64ValueBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.uint32Value_ = uint32ValueBuilder_ == null
            ? uint32Value_
            : uint32ValueBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.uint64Value_ = uint64ValueBuilder_ == null
            ? uint64Value_
            : uint64ValueBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.floatValue_ = floatValueBuilder_ == null
            ? floatValue_
            : floatValueBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.doubleValue_ = doubleValueBuilder_ == null
            ? doubleValue_
            : doubleValueBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.boolValue_ = boolValueBuilder_ == null
            ? boolValue_
            : boolValueBuilder_.build();
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.stringValue_ = stringValueBuilder_ == null
            ? stringValue_
            : stringValueBuilder_.build();
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.bytesValue_ = bytesValueBuilder_ == null
            ? bytesValue_
            : bytesValueBuilder_.build();
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amstee.flink.formats.proto.test.v1.WrapperTypesTest) {
        return mergeFrom((com.amstee.flink.formats.proto.test.v1.WrapperTypesTest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amstee.flink.formats.proto.test.v1.WrapperTypesTest other) {
      if (other == com.amstee.flink.formats.proto.test.v1.WrapperTypesTest.getDefaultInstance()) return this;
      if (other.hasInt32Value()) {
        mergeInt32Value(other.getInt32Value());
      }
      if (other.hasInt64Value()) {
        mergeInt64Value(other.getInt64Value());
      }
      if (other.hasUint32Value()) {
        mergeUint32Value(other.getUint32Value());
      }
      if (other.hasUint64Value()) {
        mergeUint64Value(other.getUint64Value());
      }
      if (other.hasFloatValue()) {
        mergeFloatValue(other.getFloatValue());
      }
      if (other.hasDoubleValue()) {
        mergeDoubleValue(other.getDoubleValue());
      }
      if (other.hasBoolValue()) {
        mergeBoolValue(other.getBoolValue());
      }
      if (other.hasStringValue()) {
        mergeStringValue(other.getStringValue());
      }
      if (other.hasBytesValue()) {
        mergeBytesValue(other.getBytesValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInt32ValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInt64ValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getUint32ValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getUint64ValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getFloatValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getDoubleValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getBoolValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getStringValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getBytesValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Int32Value int32Value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> int32ValueBuilder_;
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     * @return Whether the int32Value field is set.
     */
    public boolean hasInt32Value() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     * @return The int32Value.
     */
    public com.google.protobuf.Int32Value getInt32Value() {
      if (int32ValueBuilder_ == null) {
        return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
      } else {
        return int32ValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    public Builder setInt32Value(com.google.protobuf.Int32Value value) {
      if (int32ValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        int32Value_ = value;
      } else {
        int32ValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    public Builder setInt32Value(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (int32ValueBuilder_ == null) {
        int32Value_ = builderForValue.build();
      } else {
        int32ValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    public Builder mergeInt32Value(com.google.protobuf.Int32Value value) {
      if (int32ValueBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          int32Value_ != null &&
          int32Value_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
          getInt32ValueBuilder().mergeFrom(value);
        } else {
          int32Value_ = value;
        }
      } else {
        int32ValueBuilder_.mergeFrom(value);
      }
      if (int32Value_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    public Builder clearInt32Value() {
      bitField0_ = (bitField0_ & ~0x00000001);
      int32Value_ = null;
      if (int32ValueBuilder_ != null) {
        int32ValueBuilder_.dispose();
        int32ValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    public com.google.protobuf.Int32Value.Builder getInt32ValueBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInt32ValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder() {
      if (int32ValueBuilder_ != null) {
        return int32ValueBuilder_.getMessageOrBuilder();
      } else {
        return int32Value_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getInt32ValueFieldBuilder() {
      if (int32ValueBuilder_ == null) {
        int32ValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getInt32Value(),
                getParentForChildren(),
                isClean());
        int32Value_ = null;
      }
      return int32ValueBuilder_;
    }

    private com.google.protobuf.Int64Value int64Value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> int64ValueBuilder_;
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     * @return Whether the int64Value field is set.
     */
    public boolean hasInt64Value() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     * @return The int64Value.
     */
    public com.google.protobuf.Int64Value getInt64Value() {
      if (int64ValueBuilder_ == null) {
        return int64Value_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : int64Value_;
      } else {
        return int64ValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    public Builder setInt64Value(com.google.protobuf.Int64Value value) {
      if (int64ValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        int64Value_ = value;
      } else {
        int64ValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    public Builder setInt64Value(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (int64ValueBuilder_ == null) {
        int64Value_ = builderForValue.build();
      } else {
        int64ValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    public Builder mergeInt64Value(com.google.protobuf.Int64Value value) {
      if (int64ValueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          int64Value_ != null &&
          int64Value_ != com.google.protobuf.Int64Value.getDefaultInstance()) {
          getInt64ValueBuilder().mergeFrom(value);
        } else {
          int64Value_ = value;
        }
      } else {
        int64ValueBuilder_.mergeFrom(value);
      }
      if (int64Value_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    public Builder clearInt64Value() {
      bitField0_ = (bitField0_ & ~0x00000002);
      int64Value_ = null;
      if (int64ValueBuilder_ != null) {
        int64ValueBuilder_.dispose();
        int64ValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    public com.google.protobuf.Int64Value.Builder getInt64ValueBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInt64ValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getInt64ValueOrBuilder() {
      if (int64ValueBuilder_ != null) {
        return int64ValueBuilder_.getMessageOrBuilder();
      } else {
        return int64Value_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : int64Value_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getInt64ValueFieldBuilder() {
      if (int64ValueBuilder_ == null) {
        int64ValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getInt64Value(),
                getParentForChildren(),
                isClean());
        int64Value_ = null;
      }
      return int64ValueBuilder_;
    }

    private com.google.protobuf.UInt32Value uint32Value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> uint32ValueBuilder_;
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     * @return Whether the uint32Value field is set.
     */
    public boolean hasUint32Value() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     * @return The uint32Value.
     */
    public com.google.protobuf.UInt32Value getUint32Value() {
      if (uint32ValueBuilder_ == null) {
        return uint32Value_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : uint32Value_;
      } else {
        return uint32ValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    public Builder setUint32Value(com.google.protobuf.UInt32Value value) {
      if (uint32ValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        uint32Value_ = value;
      } else {
        uint32ValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    public Builder setUint32Value(
        com.google.protobuf.UInt32Value.Builder builderForValue) {
      if (uint32ValueBuilder_ == null) {
        uint32Value_ = builderForValue.build();
      } else {
        uint32ValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    public Builder mergeUint32Value(com.google.protobuf.UInt32Value value) {
      if (uint32ValueBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          uint32Value_ != null &&
          uint32Value_ != com.google.protobuf.UInt32Value.getDefaultInstance()) {
          getUint32ValueBuilder().mergeFrom(value);
        } else {
          uint32Value_ = value;
        }
      } else {
        uint32ValueBuilder_.mergeFrom(value);
      }
      if (uint32Value_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    public Builder clearUint32Value() {
      bitField0_ = (bitField0_ & ~0x00000004);
      uint32Value_ = null;
      if (uint32ValueBuilder_ != null) {
        uint32ValueBuilder_.dispose();
        uint32ValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    public com.google.protobuf.UInt32Value.Builder getUint32ValueBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getUint32ValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    public com.google.protobuf.UInt32ValueOrBuilder getUint32ValueOrBuilder() {
      if (uint32ValueBuilder_ != null) {
        return uint32ValueBuilder_.getMessageOrBuilder();
      } else {
        return uint32Value_ == null ?
            com.google.protobuf.UInt32Value.getDefaultInstance() : uint32Value_;
      }
    }
    /**
     * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> 
        getUint32ValueFieldBuilder() {
      if (uint32ValueBuilder_ == null) {
        uint32ValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder>(
                getUint32Value(),
                getParentForChildren(),
                isClean());
        uint32Value_ = null;
      }
      return uint32ValueBuilder_;
    }

    private com.google.protobuf.UInt64Value uint64Value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> uint64ValueBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     * @return Whether the uint64Value field is set.
     */
    public boolean hasUint64Value() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     * @return The uint64Value.
     */
    public com.google.protobuf.UInt64Value getUint64Value() {
      if (uint64ValueBuilder_ == null) {
        return uint64Value_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : uint64Value_;
      } else {
        return uint64ValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    public Builder setUint64Value(com.google.protobuf.UInt64Value value) {
      if (uint64ValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        uint64Value_ = value;
      } else {
        uint64ValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    public Builder setUint64Value(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (uint64ValueBuilder_ == null) {
        uint64Value_ = builderForValue.build();
      } else {
        uint64ValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    public Builder mergeUint64Value(com.google.protobuf.UInt64Value value) {
      if (uint64ValueBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          uint64Value_ != null &&
          uint64Value_ != com.google.protobuf.UInt64Value.getDefaultInstance()) {
          getUint64ValueBuilder().mergeFrom(value);
        } else {
          uint64Value_ = value;
        }
      } else {
        uint64ValueBuilder_.mergeFrom(value);
      }
      if (uint64Value_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    public Builder clearUint64Value() {
      bitField0_ = (bitField0_ & ~0x00000008);
      uint64Value_ = null;
      if (uint64ValueBuilder_ != null) {
        uint64ValueBuilder_.dispose();
        uint64ValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    public com.google.protobuf.UInt64Value.Builder getUint64ValueBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getUint64ValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getUint64ValueOrBuilder() {
      if (uint64ValueBuilder_ != null) {
        return uint64ValueBuilder_.getMessageOrBuilder();
      } else {
        return uint64Value_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : uint64Value_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getUint64ValueFieldBuilder() {
      if (uint64ValueBuilder_ == null) {
        uint64ValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getUint64Value(),
                getParentForChildren(),
                isClean());
        uint64Value_ = null;
      }
      return uint64ValueBuilder_;
    }

    private com.google.protobuf.FloatValue floatValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FloatValue, com.google.protobuf.FloatValue.Builder, com.google.protobuf.FloatValueOrBuilder> floatValueBuilder_;
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     * @return Whether the floatValue field is set.
     */
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     * @return The floatValue.
     */
    public com.google.protobuf.FloatValue getFloatValue() {
      if (floatValueBuilder_ == null) {
        return floatValue_ == null ? com.google.protobuf.FloatValue.getDefaultInstance() : floatValue_;
      } else {
        return floatValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    public Builder setFloatValue(com.google.protobuf.FloatValue value) {
      if (floatValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        floatValue_ = value;
      } else {
        floatValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    public Builder setFloatValue(
        com.google.protobuf.FloatValue.Builder builderForValue) {
      if (floatValueBuilder_ == null) {
        floatValue_ = builderForValue.build();
      } else {
        floatValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    public Builder mergeFloatValue(com.google.protobuf.FloatValue value) {
      if (floatValueBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          floatValue_ != null &&
          floatValue_ != com.google.protobuf.FloatValue.getDefaultInstance()) {
          getFloatValueBuilder().mergeFrom(value);
        } else {
          floatValue_ = value;
        }
      } else {
        floatValueBuilder_.mergeFrom(value);
      }
      if (floatValue_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    public Builder clearFloatValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      floatValue_ = null;
      if (floatValueBuilder_ != null) {
        floatValueBuilder_.dispose();
        floatValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    public com.google.protobuf.FloatValue.Builder getFloatValueBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getFloatValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    public com.google.protobuf.FloatValueOrBuilder getFloatValueOrBuilder() {
      if (floatValueBuilder_ != null) {
        return floatValueBuilder_.getMessageOrBuilder();
      } else {
        return floatValue_ == null ?
            com.google.protobuf.FloatValue.getDefaultInstance() : floatValue_;
      }
    }
    /**
     * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FloatValue, com.google.protobuf.FloatValue.Builder, com.google.protobuf.FloatValueOrBuilder> 
        getFloatValueFieldBuilder() {
      if (floatValueBuilder_ == null) {
        floatValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FloatValue, com.google.protobuf.FloatValue.Builder, com.google.protobuf.FloatValueOrBuilder>(
                getFloatValue(),
                getParentForChildren(),
                isClean());
        floatValue_ = null;
      }
      return floatValueBuilder_;
    }

    private com.google.protobuf.DoubleValue doubleValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> doubleValueBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     * @return Whether the doubleValue field is set.
     */
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     * @return The doubleValue.
     */
    public com.google.protobuf.DoubleValue getDoubleValue() {
      if (doubleValueBuilder_ == null) {
        return doubleValue_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : doubleValue_;
      } else {
        return doubleValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    public Builder setDoubleValue(com.google.protobuf.DoubleValue value) {
      if (doubleValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        doubleValue_ = value;
      } else {
        doubleValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    public Builder setDoubleValue(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (doubleValueBuilder_ == null) {
        doubleValue_ = builderForValue.build();
      } else {
        doubleValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    public Builder mergeDoubleValue(com.google.protobuf.DoubleValue value) {
      if (doubleValueBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          doubleValue_ != null &&
          doubleValue_ != com.google.protobuf.DoubleValue.getDefaultInstance()) {
          getDoubleValueBuilder().mergeFrom(value);
        } else {
          doubleValue_ = value;
        }
      } else {
        doubleValueBuilder_.mergeFrom(value);
      }
      if (doubleValue_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    public Builder clearDoubleValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      doubleValue_ = null;
      if (doubleValueBuilder_ != null) {
        doubleValueBuilder_.dispose();
        doubleValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    public com.google.protobuf.DoubleValue.Builder getDoubleValueBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getDoubleValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getDoubleValueOrBuilder() {
      if (doubleValueBuilder_ != null) {
        return doubleValueBuilder_.getMessageOrBuilder();
      } else {
        return doubleValue_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : doubleValue_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getDoubleValueFieldBuilder() {
      if (doubleValueBuilder_ == null) {
        doubleValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getDoubleValue(),
                getParentForChildren(),
                isClean());
        doubleValue_ = null;
      }
      return doubleValueBuilder_;
    }

    private com.google.protobuf.BoolValue boolValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> boolValueBuilder_;
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     * @return Whether the boolValue field is set.
     */
    public boolean hasBoolValue() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     * @return The boolValue.
     */
    public com.google.protobuf.BoolValue getBoolValue() {
      if (boolValueBuilder_ == null) {
        return boolValue_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : boolValue_;
      } else {
        return boolValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    public Builder setBoolValue(com.google.protobuf.BoolValue value) {
      if (boolValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        boolValue_ = value;
      } else {
        boolValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    public Builder setBoolValue(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (boolValueBuilder_ == null) {
        boolValue_ = builderForValue.build();
      } else {
        boolValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    public Builder mergeBoolValue(com.google.protobuf.BoolValue value) {
      if (boolValueBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          boolValue_ != null &&
          boolValue_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getBoolValueBuilder().mergeFrom(value);
        } else {
          boolValue_ = value;
        }
      } else {
        boolValueBuilder_.mergeFrom(value);
      }
      if (boolValue_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    public Builder clearBoolValue() {
      bitField0_ = (bitField0_ & ~0x00000040);
      boolValue_ = null;
      if (boolValueBuilder_ != null) {
        boolValueBuilder_.dispose();
        boolValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getBoolValueBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getBoolValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getBoolValueOrBuilder() {
      if (boolValueBuilder_ != null) {
        return boolValueBuilder_.getMessageOrBuilder();
      } else {
        return boolValue_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : boolValue_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getBoolValueFieldBuilder() {
      if (boolValueBuilder_ == null) {
        boolValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getBoolValue(),
                getParentForChildren(),
                isClean());
        boolValue_ = null;
      }
      return boolValueBuilder_;
    }

    private com.google.protobuf.StringValue stringValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringValueBuilder_;
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     * @return Whether the stringValue field is set.
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     * @return The stringValue.
     */
    public com.google.protobuf.StringValue getStringValue() {
      if (stringValueBuilder_ == null) {
        return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
      } else {
        return stringValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    public Builder setStringValue(com.google.protobuf.StringValue value) {
      if (stringValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stringValue_ = value;
      } else {
        stringValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    public Builder setStringValue(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValueBuilder_ == null) {
        stringValue_ = builderForValue.build();
      } else {
        stringValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    public Builder mergeStringValue(com.google.protobuf.StringValue value) {
      if (stringValueBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          stringValue_ != null &&
          stringValue_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          getStringValueBuilder().mergeFrom(value);
        } else {
          stringValue_ = value;
        }
      } else {
        stringValueBuilder_.mergeFrom(value);
      }
      if (stringValue_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    public Builder clearStringValue() {
      bitField0_ = (bitField0_ & ~0x00000080);
      stringValue_ = null;
      if (stringValueBuilder_ != null) {
        stringValueBuilder_.dispose();
        stringValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    public com.google.protobuf.StringValue.Builder getStringValueBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getStringValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder() {
      if (stringValueBuilder_ != null) {
        return stringValueBuilder_.getMessageOrBuilder();
      } else {
        return stringValue_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getStringValueFieldBuilder() {
      if (stringValueBuilder_ == null) {
        stringValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getStringValue(),
                getParentForChildren(),
                isClean());
        stringValue_ = null;
      }
      return stringValueBuilder_;
    }

    private com.google.protobuf.BytesValue bytesValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> bytesValueBuilder_;
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     * @return Whether the bytesValue field is set.
     */
    public boolean hasBytesValue() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     * @return The bytesValue.
     */
    public com.google.protobuf.BytesValue getBytesValue() {
      if (bytesValueBuilder_ == null) {
        return bytesValue_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : bytesValue_;
      } else {
        return bytesValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    public Builder setBytesValue(com.google.protobuf.BytesValue value) {
      if (bytesValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bytesValue_ = value;
      } else {
        bytesValueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    public Builder setBytesValue(
        com.google.protobuf.BytesValue.Builder builderForValue) {
      if (bytesValueBuilder_ == null) {
        bytesValue_ = builderForValue.build();
      } else {
        bytesValueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    public Builder mergeBytesValue(com.google.protobuf.BytesValue value) {
      if (bytesValueBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          bytesValue_ != null &&
          bytesValue_ != com.google.protobuf.BytesValue.getDefaultInstance()) {
          getBytesValueBuilder().mergeFrom(value);
        } else {
          bytesValue_ = value;
        }
      } else {
        bytesValueBuilder_.mergeFrom(value);
      }
      if (bytesValue_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    public Builder clearBytesValue() {
      bitField0_ = (bitField0_ & ~0x00000100);
      bytesValue_ = null;
      if (bytesValueBuilder_ != null) {
        bytesValueBuilder_.dispose();
        bytesValueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    public com.google.protobuf.BytesValue.Builder getBytesValueBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getBytesValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    public com.google.protobuf.BytesValueOrBuilder getBytesValueOrBuilder() {
      if (bytesValueBuilder_ != null) {
        return bytesValueBuilder_.getMessageOrBuilder();
      } else {
        return bytesValue_ == null ?
            com.google.protobuf.BytesValue.getDefaultInstance() : bytesValue_;
      }
    }
    /**
     * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> 
        getBytesValueFieldBuilder() {
      if (bytesValueBuilder_ == null) {
        bytesValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>(
                getBytesValue(),
                getParentForChildren(),
                isClean());
        bytesValue_ = null;
      }
      return bytesValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amstee.flink.formats.proto.test.v1.WrapperTypesTest)
  }

  // @@protoc_insertion_point(class_scope:amstee.flink.formats.proto.test.v1.WrapperTypesTest)
  private static final com.amstee.flink.formats.proto.test.v1.WrapperTypesTest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amstee.flink.formats.proto.test.v1.WrapperTypesTest();
  }

  public static com.amstee.flink.formats.proto.test.v1.WrapperTypesTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WrapperTypesTest>
      PARSER = new com.google.protobuf.AbstractParser<WrapperTypesTest>() {
    @java.lang.Override
    public WrapperTypesTest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WrapperTypesTest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WrapperTypesTest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.amstee.flink.formats.proto.test.v1.WrapperTypesTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

