// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flink/formats/proto/test/v1/test_wrapper_types.proto

// Protobuf Java Version: 3.25.3
package com.amstee.flink.formats.proto.test.v1;

public interface WrapperTypesTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amstee.flink.formats.proto.test.v1.WrapperTypesTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
   * @return Whether the int32Value field is set.
   */
  boolean hasInt32Value();
  /**
   * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
   * @return The int32Value.
   */
  com.google.protobuf.Int32Value getInt32Value();
  /**
   * <code>.google.protobuf.Int32Value int32Value = 1 [json_name = "int32Value"];</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
   * @return Whether the int64Value field is set.
   */
  boolean hasInt64Value();
  /**
   * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
   * @return The int64Value.
   */
  com.google.protobuf.Int64Value getInt64Value();
  /**
   * <code>.google.protobuf.Int64Value int64Value = 2 [json_name = "int64Value"];</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getInt64ValueOrBuilder();

  /**
   * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
   * @return Whether the uint32Value field is set.
   */
  boolean hasUint32Value();
  /**
   * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
   * @return The uint32Value.
   */
  com.google.protobuf.UInt32Value getUint32Value();
  /**
   * <code>.google.protobuf.UInt32Value uint32Value = 3 [json_name = "uint32Value"];</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getUint32ValueOrBuilder();

  /**
   * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
   * @return Whether the uint64Value field is set.
   */
  boolean hasUint64Value();
  /**
   * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
   * @return The uint64Value.
   */
  com.google.protobuf.UInt64Value getUint64Value();
  /**
   * <code>.google.protobuf.UInt64Value uint64Value = 4 [json_name = "uint64Value"];</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getUint64ValueOrBuilder();

  /**
   * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
   * @return Whether the floatValue field is set.
   */
  boolean hasFloatValue();
  /**
   * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
   * @return The floatValue.
   */
  com.google.protobuf.FloatValue getFloatValue();
  /**
   * <code>.google.protobuf.FloatValue floatValue = 5 [json_name = "floatValue"];</code>
   */
  com.google.protobuf.FloatValueOrBuilder getFloatValueOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
   * @return Whether the doubleValue field is set.
   */
  boolean hasDoubleValue();
  /**
   * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
   * @return The doubleValue.
   */
  com.google.protobuf.DoubleValue getDoubleValue();
  /**
   * <code>.google.protobuf.DoubleValue doubleValue = 6 [json_name = "doubleValue"];</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDoubleValueOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
   * @return Whether the boolValue field is set.
   */
  boolean hasBoolValue();
  /**
   * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
   * @return The boolValue.
   */
  com.google.protobuf.BoolValue getBoolValue();
  /**
   * <code>.google.protobuf.BoolValue boolValue = 7 [json_name = "boolValue"];</code>
   */
  com.google.protobuf.BoolValueOrBuilder getBoolValueOrBuilder();

  /**
   * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
   * @return The stringValue.
   */
  com.google.protobuf.StringValue getStringValue();
  /**
   * <code>.google.protobuf.StringValue stringValue = 8 [json_name = "stringValue"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder();

  /**
   * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
   * @return Whether the bytesValue field is set.
   */
  boolean hasBytesValue();
  /**
   * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
   * @return The bytesValue.
   */
  com.google.protobuf.BytesValue getBytesValue();
  /**
   * <code>.google.protobuf.BytesValue bytesValue = 9 [json_name = "bytesValue"];</code>
   */
  com.google.protobuf.BytesValueOrBuilder getBytesValueOrBuilder();
}
